### Default values for the PAS Async Worker Helm Chart.
### This is a YAML-formatted file.
### Declare variables to be passed into your templates.

## Options & settings accessible by all charts
global:
  ## Provide a name in place of `sde` for `app:` labels
  ##
  #nameOverride: ""

  ## Provide a name to substitute for the full names of resources
  ##
  #fullnameOverride: ""

  ## Configuration options and crentials to fetch images from private
  ## registries/repositories. These are provided by SDElements support staff on
  ## request upon purchase of the SDElements product.
  ##
  imageRegistry: docker.sdelements.com
  #imageRegistry: docker-dev.sdelements.com

  # Format: $imageRegistry $imageOrganization $imageSource $imageName $imageTag
  # docker.sdelements.com / default_organization - (sde/3rd) - cert-creator : latest
  # docker-dev.sdelements.com / dev _ (sde/3rd) / cert-creator : latest
  #imageRegistryFormat: "%s/%s_%s/%s:%s"
  imageRegistryFormat: "%s/%s-%s-%s:%s"
  imageRegistryUsername: acmecorp
  imageRegistryPassword: SuperSecretPassword
  imageOrganization: default_organization
  #imageOrganization: dev
  imagePullPolicy: IfNotPresent
  #imageSource: sde
  #
  # Fully Qualified Domain Name(s)
  #
  # fqdn: example.com
  # DNS Aliases & Extra names
  # FQDN and alternateDnsNames are used to create DNS records and
  # get certificates issued dynamically.
  # Connections to URLs defined in these are encrypted by default using Cert Manager
  # and if not defined will fall back to Custom Certs/self-signed Certs.
  # alternateDnsNames:
  #  - alias.example.com
  #  - othername.example.com
  # alternateVirtualHosts are used to create config sections in the ingress and
  # can be optionally used with a custom cert.
  # When custom certs are configured any connections to these URLs will be encrypted using said certs,
  # in case custom certs are not configured the ingress will back to using self signed certs.
  # alternateVirtualHosts:
  #  - externally-managed-dns-record.example.com

  ## Feature flags that enable/disable subcharts and subchart features
  # that need to be specified before runtime because they affect how subcharts
  # deploy themselves
  #

  pas:
    #databasePrefix: pas
    #enableCustomPlugins: true
    #maxPluginFileSize: 10000000

    # Name of the plugin service celery queue to listen on
    #pluginServiceQueueName: plugin_service_worker
    # Name of the async worker celery queue to listen on
    #asyncWorkerQueueName: pas_async_worker
    ## Volume claim name for custom plugins.
    ## Specifying this value implies the use of an external volume so the default volume claim will not be created.
    #pluginVolumeClaimName: pas-custom-plugin-volume-claim
    # Global PAS broker config
    broker: {}
      ## Username for broker user
      #user: pas
      #password:
      #secretName:
      #passwordSecretKey:
      #vhost:
    # Global PAS database config
    database: {}
      #user: pas
      #password:
      #secretName:
      #passwordSecretKey:

  database:
    adminClientUser: sde

  broker: {}
    #adminClientUser: sde
    #adminVhost: sde

#  enableNodeSelector: true


## Chart Configuration
# Include broker subchart in deployment
useBrokerSubchart: true
# Include database subchart in deployment
useDatabaseSubchart: true
# Include plugin volume claim
includePluginVolumeClaim: true

## PAS Async Worker container configuration
#imageName: pas-async-worker
##  Default image tag.
#imageTag: <App Version>
## Celery result backend
#resultBackend: rpc://
## Celery queue names
#asyncWorkerQueueName: pas_async_worker
#pluginServiceQueueName: plugin_service_worker
## Celery log level. One of DEBUG, INFO, WARNING, ERROR, CRITICAL
#celeryLogLevel: INFO
## Number of celery worker processes to launch
#celeryWorkerCount: 4
## Max number of celery tasks before recreating the worker.
## Lowering the amount can help keep memory usage lower over time.
#celeryMaxTasksPerChild: 10
#customPluginVolumeSize: 2Gi

## Volume claim name for custom plugins.
## Specifying this value implies the use of an external volume so the default volume claim will not be created.
#pluginVolumeClaimName: pas-custom-plugin-volume-claim

# PAS broker config
broker: {}
  #secretName:
  #passwordSecretKey:

# PAS database config
database: {}
  #secretName:
  #passwordSecretKey:
