{{- $claimName := printf "%v-%v" .Release.Name "broker-volume-claim" -}}
{{- $storageClassName:= default .Values.global.storageClass .Values.storageClass -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-broker-volume-claim
  labels:
    {{- include "library.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "50M" .Values.brokerVolumeSize }}
  {{ if $storageClassName -}}
  storageClassName: {{ $storageClassName | quote }}
  {{- end }}
status: {}
