{{- $serviceName := printf "%v-%v-%v" ( include "library.trimmedName" . ) "broker" "service" -}}
{{- $deploymentName := printf "%v-%v" ( include "library.trimmedName" . ) "broker" -}}
{{- $port := default 5672 .Values.port -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName | quote }}
  labels:
    service: {{ $serviceName | quote }}
    {{- include "library.labels" . | nindent 4 }}
spec:
  ports:
  - name: {{ printf "%d" $port | quote }}
    port: {{ $port }}
    targetPort: {{ $port }}
  - name: "15672"
    port: 15672
    targetPort: 15672
  selector:
    name: {{ $deploymentName | quote }}
status:
  loadBalancer: {}
