apiVersion: v2
appVersion: 2022.2.68
dependencies:
- condition: sde.enableJITT
  name: sc-jitt
  repository: https://harbor-dev.sdelements.com/chartrepo/library
  version: 2022.2.7
- name: sc-library
  repository: https://harbor-dev.sdelements.com/chartrepo/library
  version: 0.1.1
- condition: sc-database.enabled
  name: sc-database
  repository: https://harbor-dev.sdelements.com/chartrepo/library
  version: 1.2.4
- name: sc-broker
  repository: https://harbor-dev.sdelements.com/chartrepo/library
  version: 1.2.1
- name: sc-mail
  repository: https://harbor-dev.sdelements.com/chartrepo/library
  version: 0.0.15
- condition: ingress-nginx.enabled
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  tags:
  - nlb
  - aws
  version: 4.0.19
- condition: global.pas.enabled
  name: pas
  repository: https://harbor-dev.sdelements.com/chartrepo/library
  version: 1.5.1
- condition: minio.enabled
  name: minio
  repository: https://charts.min.io/
  version: 3.4.6
description: SDElements by Security Compass Ltd.
icon: https://avatars0.githubusercontent.com/u/739346
keywords:
- security appsec code secure
maintainers:
- email: devops-support@securitycompass.com
  name: Security Compass Technologies Ltd.
  url: https://www.securitycompass.com/
name: sde
type: application
version: 2022.2.68-bb.1
