apiVersion: v2
appVersion: 2024.4.38
dependencies:
- condition: sde.enableJITT
  name: sc-jitt
  repository: https://repository.securitycompass.com/artifactory/sde-helm-dev
  version: 2024.4.3
- name: sc-library
  repository: https://repository.securitycompass.com/artifactory/sde-helm-dev
  version: 1.1.5
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 15.5.23
- condition: rabbitmq.enabled
  name: rabbitmq
  repository: https://charts.bitnami.com/bitnami
  version: 14.7.0
- name: sc-datastore
  repository: https://repository.securitycompass.com/artifactory/sde-helm-dev
  version: 1.0.14
- name: sc-mail
  repository: https://repository.securitycompass.com/artifactory/sde-helm-dev
  version: 0.1.18
- condition: ingress-nginx.enabled
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  tags:
  - nlb
  - aws
  version: 4.8.2
- condition: global.pas.enabled
  name: pas
  repository: https://repository.securitycompass.com/artifactory/sde-helm-dev
  version: 2.0.6
- condition: minio.enabled
  name: minio
  repository: https://charts.min.io/
  version: 5.2.0
- alias: minio-tenant
  condition: minio-tenant.enabled
  name: tenant
  repository: https://operator.min.io
  version: 5.0.12
description: SDElements by Security Compass Ltd.
icon: https://avatars0.githubusercontent.com/u/739346
keywords:
- security appsec code secure
maintainers:
- email: sdesupport@securitycompass.com
  name: Security Compass Technologies Ltd.
  url: https://www.securitycompass.com/
name: sde
type: application
version: 2024.4.38-bb.3
