apiVersion: v2
appVersion: 2023.2.49
dependencies:
- condition: sde.enableJITT
  name: sc-jitt
  repository: https://repository.securitycompass.com/artifactory/sde-helm-dev
  version: 2023.2.2
- name: sc-library
  repository: https://repository.securitycompass.com/artifactory/sde-helm-dev
  version: 1.1.4
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.4.2
- condition: rabbitmq.enabled
  name: rabbitmq
  repository: https://charts.bitnami.com/bitnami
  version: 11.14.4
- name: sc-datastore
  repository: https://repository.securitycompass.com/artifactory/sde-helm-dev
  version: 1.0.5
- name: sc-mail
  repository: https://repository.securitycompass.com/artifactory/sde-helm-dev
  version: 0.1.11
- condition: ingress-nginx.enabled
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  tags:
  - nlb
  - aws
  version: 4.6.0
- condition: global.pas.enabled
  name: pas
  repository: https://repository.securitycompass.com/artifactory/sde-helm-dev
  version: 1.8.0
- condition: minio.enabled
  name: minio
  repository: https://charts.min.io/
  version: 5.0.8
- condition: sc-cam.enabled
  name: sc-cam
  repository: https://repository.securitycompass.com/artifactory/sde-helm-dev
  version: 0.0.22
description: SDElements by Security Compass Ltd.
icon: https://avatars0.githubusercontent.com/u/739346
keywords:
- security appsec code secure
maintainers:
- email: devops-support@securitycompass.com
  name: Security Compass Technologies Ltd.
  url: https://www.securitycompass.com/
name: sde
type: application
version: 2023.2.49-bb.1
