apiVersion: v2
appVersion: 2023.1.54
dependencies:
- condition: sde.enableJITT
  name: sc-jitt
  repository: https://repository.securitycompass.com/artifactory/sde-helm-dev
  version: 2023.1.0
- name: sc-library
  repository: https://repository.securitycompass.com/artifactory/sde-helm-dev
  version: 1.1.4
- condition: sc-database.enabled
  name: sc-database
  repository: https://repository.securitycompass.com/artifactory/sde-helm-dev
  version: 1.3.6
- name: sc-broker
  repository: https://repository.securitycompass.com/artifactory/sde-helm-dev
  version: 1.3.7
- name: sc-datastore
  repository: https://repository.securitycompass.com/artifactory/sde-helm-dev
  version: 1.0.4
- name: sc-mail
  repository: https://repository.securitycompass.com/artifactory/sde-helm-dev
  version: 0.1.9
- condition: ingress-nginx.enabled
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  tags:
  - nlb
  - aws
  version: 4.6.0
- condition: global.pas.enabled
  name: pas
  repository: https://repository.securitycompass.com/artifactory/sde-helm-dev
  version: 1.7.9
- condition: minio.enabled
  name: minio
  repository: https://charts.min.io/
  version: 5.0.8
description: SDElements by Security Compass Ltd.
icon: https://avatars0.githubusercontent.com/u/739346
keywords:
- security appsec code secure
maintainers:
- email: devops-support@securitycompass.com
  name: Security Compass Technologies Ltd.
  url: https://www.securitycompass.com/
name: sde
type: application
version: 2023.1.54
