{{- $imageName := default "pas-plugin-service" .Values.imageName -}}
{{- $imageTag := default .Chart.AppVersion .Values.imageTag -}}
{{- $imagePullPolicy := default .Values.global.imagePullPolicy .Values.imagePullPolicy -}}
{{- $imageRegistry := required "An image registry needs to be specified in your configuration values!" .Values.global.imageRegistry -}}
{{- $imageOrganization := required "An image organization needs to be specified in your configuration values!" .Values.global.imageOrganization -}}
{{- $imageSource := default ( default "sde" .Values.global.imageSource ) .Values.imageSource -}}
{{- $imageRegistryFormat := default "%s/%s-%s-%s:%s" .Values.global.imageRegistryFormat -}}

{{- $deploymentName := printf "%v-%v" ( include "library.trimmedName" . ) "pas-plugin-worker" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName | quote }}
  labels:
    name: {{ $deploymentName | quote }}
    {{- include "library.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.replicas }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      name: {{ $deploymentName | quote }}
      {{- include "library.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ $deploymentName | quote }}
        {{- include "library.selectorLabels" . | nindent 8 }}
    spec:
      {{ if .Values.global.enableNodeSelector }}
      nodeSelector:
        customer_name: {{ printf "%v" .Release.Name | quote }}
      {{ end }}
      {{- if not ((.Values.global.openshift).enabled) }}
      securityContext:
        {{- if not .Values.global.runAsRoot }}
        runAsUser: {{ default 100 .Values.uid }}
        runAsGroup: {{ default 101 .Values.gid }}
        {{- if semverCompare ">=1.23.0-0" .Capabilities.KubeVersion.GitVersion }}
        fsGroupChangePolicy: "OnRootMismatch"
        {{- end }}
        {{- else }}
        runAsUser: 0
        runAsGroup: 0
        {{- end }}
      {{- end }}
      containers:
      - name: {{ $deploymentName | quote }}
        image: {{ printf $imageRegistryFormat $imageRegistry $imageOrganization $imageSource $imageName $imageTag | quote }}
        imagePullPolicy: {{ $imagePullPolicy }}
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-{{ .Chart.Name }}-env-configmap
          - configMapRef:
              name: {{ .Release.Name }}-{{ .Chart.Name }}-broker-env-configmap
          - configMapRef:
              name: {{ .Release.Name }}-{{ .Chart.Name }}-shared-storage-env-configmap
        env:
          - name: PLUGIN_SERVICE_BROKER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "pas-plugin-worker.broker.secretName" (dict "root" . "dot" .Values) }}
                key: {{ include "pas-plugin-worker.broker.passwordSecretKey" (dict "root" . "dot" .Values) }}
          - name: S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: {{ include "pas-plugin-worker.sharedStorage.secretName" (dict "root" . "dot" .Values) }}
                key: {{ include "pas-plugin-worker.sharedStorage.accessKeyIdSecretKey" (dict "root" . "dot" .Values) }}
          - name: S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "pas-plugin-worker.sharedStorage.secretName" (dict "root" . "dot" .Values) }}
                key: {{ include "pas-plugin-worker.sharedStorage.secretAccessKeySecretKey" (dict "root" . "dot" .Values) }}
      imagePullSecrets:
      - name: {{ include "library.registrySecretName" . }}
      restartPolicy: Always
status: {}
