# Sentry variables
{{- $sentryEnabled := default false (eq ((.Values.sentry).enabled | toString) "<nil>" | ternary (.Values.global.sentry).enabled (.Values.sentry).enabled) -}}
{{- $sentryDSN := (.Values.sentry).dsn }}
{{- $sentryEnvironment := default .Release.Namespace (default (.Values.global.sentry).environment (.Values.sentry).environment) }}
{{- $sentrySampleRate := default 0.1 (default (.Values.global.sentry).sampleRate (.Values.sentry).sampleRate) }}
{{- $sentryTraceSampleRate := default 0.1 (default (.Values.global.sentry).traceSampleRate (.Values.sentry).traceSampleRate) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-env-configmap
  labels:
    {{ include "library.labels" . | nindent 4 }}
data:
  {{ if .Values.celeryLogLevel }}
  PAS_CONSOLE_LOG_LEVEL: {{ .Values.celeryLogLevel }}
  {{ end }}
  {{ if .Values.celeryMaxTasksPerChild }}
  MAX_TASKS: {{ .Values.celeryMaxTasksPerChild }}
  {{ end }}
  {{ if ((.Values.global).runAsRoot) }}
  C_FORCE_ROOT: "true"
  {{ end }}
  {{ if .Values.celeryWorkerCount }}
  CELERY_WORKER_COUNT: {{ .Values.celeryWorkerCount }}
  {{ end }}
  {{ if $sentryEnabled }}
  SDE_PAS_PLUGINS_SENTRY_DSN: {{ required "SDE_PAS_PLUGINS_SENTRY_DSN must be specified if Sentry configuration is enabled." $sentryDSN | quote }}
  SDE_SENTRY_ENVIRONMENT: {{ $sentryEnvironment | quote }}
  SDE_SENTRY_SAMPLE_RATE: {{ $sentrySampleRate | quote }}
  SDE_SENTRY_TRACE_SAMPLE_RATE: {{ $sentryTraceSampleRate | quote }}
  {{ end }}
  {{ if .Values.syncTaskTimeoutSeconds }}
  PLUGIN_SERVICE_SYNC_TASK_TIMEOUT_SECONDS: {{ .Values.syncTaskTimeoutSeconds | quote }}
  {{ end }}
  {{- if .Values.global.thirdPartyCACertificates.enabled }}
  TRUST_THIRDPARTY_CA_CERTS: "true"
  {{- end }}
