global:
  imageRegistryUsername: <YOUR IRONBANK USERNAME>
  imageRegistryPassword: <YOUR IRONBANK PASSWORD>
  imageRegistry: registry1.dso.mil
  imageRegistryFormat: "%s/%s/%s/%s:%s"
  imagePullPolicy: Always
  imageOrganization: ironbank/security-compass
  imageSource: sd-elements
  imageTag: 2024.1.42
  storageClass: gp2 # Should be any RWO storageclass with dynamic provisioning, if possible
  sharedStorage:
    bucketName: <NAME-OF-THE-BUCKET>
    s3Url: https://s3.<region>.amazonaws.com
    s3AccessKey: <S3-ACCESS-KEY>
    s3SecretKey: <S3-SECRET-KEY>
  rwx:
    enabled: false
  nginxIngress:
    enabled: false # This will stop the creation of an Ingress resource, which isn't required when using Istio.
sde:
  fqdn: <YOUR-SDE-FQDN>
  jwtSecret: <YOUR-JWT-SECRET>
  secretKey: <YOUR-SECRET-KEY>
  superuserPassword: <YOUR-SUPERUSER-PASSWORD>
  enableJITT: false
web:
  replicas: 1
  imageName: nginx
  imageTag: 2024.1.42-9.4-001
  uid: 993
  gid: 993
  fsgid: 49
sc-jitt:
  replicas: 1
  imageSource: jitt
  imageName: nginx
  imageTag: 2024.1.1-9.4-001
  uid: 993
  gid: 993
  fsgid: 49
rabbitmq:
    replicaCount: 1
    image:
        repository: ironbank/bitnami/rabbitmq
        tag: 3.12.14
    auth:
        password: <YOUR-BROKER-PASSWORD>
        erlangCookie: <YOUR-BROKER-ERLANG-COOKIE>
    ## User/Group options
    containerSecurityContext:
        runAsUser: 1001
    podSecurityConext:
        fsGroup: 1001
    initContainers: []
    extraEnvVars: []
postgresql:
  image:
    repository: ironbank/opensource/postgres/postgresql12
    tag: 12.19
  postgresql:
    auth:
      password: <YOUR-DATABASE-PASSWORD>
  ## User/Group options
  primary:
    containerSecurityContext:
      runAsUser: 26
      runAsGroup: 26
    podSecurityContext:
      fsGroup: 26
sc-mail:
  imageName: exim
  imageTag: 1.4-9.4-001
worker:
  imageName: mod_wsgi
  imageTag: 2024.1.42-9.4-001
  uid: 48
  gid: 48
  fsgid: 49
reporting:
  enabled: true
  imageName: reporting
  imageTag: 2024.1.42-9.4-001
  enableTls: true
  uid: 1001
  gid: 1001
  nginxuid: 993
  nginxgid: 993
  replicas: 1
sc-datastore:
  clientPassword: <YOUR-DATASTORE-PASSWORD>
  imageOrganization: ironbank/opensource
  imageSource: redis
  imageName: redis6
  imageTag: 6.2.14-ubi9
  uid: 1001
  gid: 1001
  fsgid: 1001
  replicas: 1
sc-cam:
  brokerPassword: <YOUR-BROKER-PASSWORD>
  databasePassword: <YOUR-DATABASE-PASSWORD>
  enabled: true
  mageName: cam
  imageTag: 2024.1.5-9.4-001
  initImageName: common-init
  initImageTag: 2024.1.2-8.10-001
  uid: 1001
  gid: 1001
job:
  specifications:
    trend-reporting:
      imageTag: 2024.1.4-8.10-001
      uid: 998
      gid: 996
      fsgid: 996
# The settings below are for adjusting the big bang customizations
istio:
  enabled: true
  gateways:
    - istio-system/public
  host: sdelements.bigbang.dev
efsVolumes:
  enabled: false
networkPolicies:
  enabled: true
