# Service variables
{{ $runAsSubchart := default false .Values.enable }}
{{- $serviceName := default ( printf "%v-%v-%v" .Release.Name "project-creation-automation" "service" ) ( .Values.serviceName ) -}}
{{- $deploymentName := printf "%v-%v" .Release.Name "project-creation-automation" -}}
{{- $httpPort := default 8001 .Values.httpPort -}}
{{- $httpsPort := default 443 .Values.httpsPort -}}

# Ingress variables
{{- $ingressName := printf "%v-%v-%v" .Release.Name "pca-web" "ingress" -}}
{{- $secretName := printf "%v-%v" .Release.Name "pca-secrets" -}}

# Only create ingress if not sharing ingress
{{ if not $runAsSubchart -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $ingressName | quote }}
  labels:
    service: {{ $ingressName | quote }}
    {{- include "pca.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "90"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "90"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
spec:
  backend:
    serviceName: {{ $serviceName | quote }}
    servicePort: {{ $httpPort }}
status:
  loadBalancer: {}
{{ end -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName | quote }}
  labels:
    service: {{ $serviceName | quote }}
    {{- include "pca.labels" . | nindent 4 }}
spec:
  ports:
  - name: {{ $httpPort | quote }}
    port: {{ $httpPort }}
    targetPort: {{ $httpPort }}
  - name: {{ $httpsPort | quote }}
    port: {{ $httpsPort }}
    targetPort: {{ $httpsPort }}
  selector:
      name: {{ $deploymentName | quote }}
status:
  loadBalancer: {}
