{{- $secretName := printf "%v-%v" .Release.Name "pca-secrets" -}}
{{- if and .Values.tlsCertificatePath ( and .Values.tlsKeyPath .Values.tlsDHParamPath ) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName | quote }}
  labels:
    #{{/*- include "sde.labels" . | nindent 4 */}}
# type: kubernetes.io/tls
data:
  pca.crt: {{ .Files.Get .Values.tlsCertificatePath | b64enc }}
  pca.key: {{ .Files.Get .Values.tlsKeyPath | b64enc }}
  pca.dhp: {{ .Files.Get .Values.tlsDHParamPath |  b64enc }}
{{- end }}
