{{- $mapName := printf "%v-%v" .Release.Name "pca-config" -}}
{{- $claimName := printf "%v-%v" .Release.Name "pca-volume-claim" -}}
{{- $storageSize := default "10Mi" .Values.storageSize -}}
{{- $storageClass := default .Values.storageClass .Values.global.storageClass -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ quote $mapName }}
  labels:
    {{- include "pca.labels" . | nindent 4 }}
data:
  # Custom config file
  {{- printf "%s: |" "settings.cfg" | nindent 2}}
  {{- include "pca.settings" $ | nindent 4 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $claimName | quote }}
  labels:
    service: {{ $claimName | quote }}
    {{- include "pca.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ $storageSize | quote }}
  {{ if $storageClass -}}
  storageClassName: {{ $storageClass }}
  {{- end }}
status: {}
