{{- $claimName := printf "%v-%v" .Release.Name "pca-tls-volume-claim" -}}
{{- $storageClass := default .Values.storageClass .Values.global.storageClass -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $claimName | quote }}
  labels:
    service: {{ $claimName | quote }}
    {{- include "pca.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: "10Mi"
  {{ if $storageClass -}}
  storageClassName: {{ $storageClass }}
  {{- end }}
status: {}
