apiVersion: v2
appVersion: 0.1.11
dependencies:
- condition: global.enableNestedDependencies
  name: sc-library
  repository: https://sdelements.jfrog.io/artifactory/sde-helm-dev
  version: 1.1.4
description: The Security Compass SMTP mail relay (Exim)
icon: https://avatars0.githubusercontent.com/u/739346
keywords:
- mail
- smtp
- ses
- gmail
- relay
- email
maintainers:
- email: devops-support@securitycompass.com
  name: Security Compass Technologies Ltd.
  url: https://www.securitycompass.com/
name: sc-mail
sources:
- https://agra.sdelements.com/deployment/containers/mail
type: application
version: 0.1.11
