{{/*
#### SDElements job template ####

Expects a dict input with root/dot keys with context

*/}}
{{- define "sde.job" -}}
{{- $root := get . "root" -}}
{{- $dot := get . "dot" -}}
{{- $jobName := get . "jobName" -}}
{{- $worker := $root.Values.worker -}}
{{- $global := $root.Values.global -}}
{{- $imagePullPolicy := $dot.imagePullPolicy | default $global.imagePullPolicy | default "IfNotPresent" -}}
{{- $imageRegistryFormat := $dot.imageRegistryFormat | default $global.imageRegistryFormat | default "%s/%s-%s-%s:%s"  -}}
{{- $imageRegistry := $dot.imageRegistry  | default $global.imageRegistry | required "An image registry needs to be specified in your configuration values!" -}}
{{- $imageOrganization := $dot.imageOrganization  | default $worker.imageOrganization | default $global.imageOrganization  | required "An image organization needs to be specified in your configuration values!" -}}
{{- $imageSource := $dot.imageSource  | default $worker.imageSource | default $global.imageSource | default "sde"  -}}
{{- $imageName := $dot.imageName |  default $worker.imageName | default "web-dynamic" -}}
{{- $workerTag := $worker.imageTag | default $global.imageTag | default $root.Chart.AppVersion | toString -}}
{{- $imageTag := $dot.imageTag |  default $workerTag | toString -}}
{{- $releaseName := printf "%v-job-%v" ( include "library.trimmedName" $root | trunc 10 ) $jobName | trimSuffix "-" -}}
{{- $uid := $dot.uid | default $worker.uid | default 33 -}}
{{- $gid := $dot.gid | default $worker.gid | default 33 -}}
{{- $fsgid := $dot.fsgid | default $worker.fsgid | default 33 -}}
{{- $failedJobsHistoryLimit := default (default 1 $root.Values.job.failedJobsHistoryLimit) $dot.failedJobsHistoryLimit -}}
{{- $successfulJobsHistoryLimit := default (default 0 $root.Values.job.successfulJobsHistoryLimit) $dot.successfulJobsHistoryLimit -}}
{{- $enableRandomStartDelay := default (default false $root.Values.job.enableRandomStartDelay) $dot.enableRandomStartDelay -}}
{{- $randomStartDelayRange := default (default "1-600" $root.Values.job.randomStartDelayRange) $dot.randomStartDelayRange -}}

{{/*
     TLS Configurations
     These tls artifacts are created in the datastore deployment
     service templates
*/}}
{{- $enableInternalTls := eq ( include "enableInternalTls" ( merge . $root ) ) "true" -}}
{{- $tlsRoot := default "/tls" $root.Values.web.tlsRoot }}

{{- $resourceLimits :=  default $root.Values.job.resources $dot.resources }}
{{/* 
    If trend reporting is disabled and the job is trend-reporting, don't create the cronjob 
*/}}
{{- if or ( $root.Values.trendReporting.enabled ) ( ne $jobName "trend-reporting" ) -}}
---
{{- if semverCompare "<1.21-0" .Capabilities.KubeVersion.Version -}}
apiVersion: batch/v1beta1
{{- else }}
apiVersion: batch/v1
{{- end }}
kind: CronJob
metadata:
  name: {{ $releaseName | quote }}
  labels:
    name: {{ $releaseName | quote }}
    {{- include "library.labels" $root | nindent 4 }}
spec:
  schedule: {{ required "Jobs are required to have a cron style schedule" $dot.schedule | quote }}
  concurrencyPolicy: {{ default "Forbid" $dot.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ $failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ $successfulJobsHistoryLimit }}
  suspend: {{ default false $dot.suspend }}
  jobTemplate:
    metadata:
      labels:
        name: {{ $releaseName | quote }}
        {{- include "library.selectorLabels" $root | nindent 8 }}
    spec:
      template:
        metadata:
          labels:
            app: {{ $releaseName }}
            cron: {{ $releaseName }}
        spec:
          {{- if not (($global.openshift).enabled) }}
          securityContext:
            {{- if not $global.runAsRoot }}
            runAsUser: {{ $uid }}
            runAsGroup: {{ $gid }}
            fsGroup: {{ $fsgid }}
            {{- if semverCompare ">=1.23.0-0" $root.Capabilities.KubeVersion.GitVersion }}
            fsGroupChangePolicy: "OnRootMismatch"
            {{- end }}
            {{- else }}
            runAsUser: 0
            runAsGroup: 0
            {{- end }}
          {{- end }}
          {{- if ( or $dot.initContainers $enableRandomStartDelay ) }}
          initContainers:
          {{- with $dot.initContainers }}
          {{ toYaml . | nindent 10 }}
          {{- end }}
          {{- if $enableRandomStartDelay }}
          - name: {{ printf "%v-%v" $releaseName "sleep" | quote }}
            {{- /* Only image we can guarantee a customer has in their custom image registry is the SDE container */}}
            image: {{ printf $imageRegistryFormat $imageRegistry $imageOrganization $imageSource "web-dynamic" $workerTag | quote }}
            imagePullPolicy: {{ $imagePullPolicy }}
            command: ['/bin/bash', '-c', 'wait=$(shuf --input-range={{ $randomStartDelayRange }} --head-count=1); echo "$(date): Waiting for ${wait} seconds..."; sleep "${wait}"; echo "$(date): Done waiting!"' ]
          {{- end }}
          {{- end }}
          containers:
          - name: {{ $releaseName | quote }}
            image: {{ printf $imageRegistryFormat $imageRegistry $imageOrganization $imageSource $imageName $imageTag | quote }}
            {{- if $dot.imagePullPolicy }}
            imagePullPolicy:  {{ $imagePullPolicy }}
            {{- end }}
            command: {{ required "Jobs are required to specify a command to run"  $dot.command }}
            env:
            {{- dict "root" $root "dot" $dot | include "sde.environment" | nindent 12}}
            {{- with $dot.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: ENSURE_DB_UNLOCKED
              value: "true"
            {{- /* If trend reporting is enabled and the job runs trend reporting container, or job has custom envFrom */}}
            {{- if ( ( $root.Values.trendReporting.enabled | and ( eq $imageName "trend-reporting" ) ) | or $dot.envFrom ) }}
            envFrom:
            {{- /* If the job is trend-reporting, attach trend reporting env */}}
            {{- if ( eq $jobName "trend-reporting" ) }}
            - secretRef:
                name: "{{ include "library.trimmedName" . }}-tr-env"
            {{- end }}
            {{- with $dot.envFrom }}
              {{ toYaml . | nindent 12 }}
            {{- end }}
            {{- end}}
            {{- if $dot.args }}
            args:
              {{- with $dot.args }}
                {{- toYaml . | nindent 12 }}
              {{- end }}
            {{- end }}
            {{- if $resourceLimits }}
            resources:
              {{- with $resourceLimits }}
                {{- toYaml . | nindent 14 }}
              {{- end }}
            {{- end }}
            {{- if semverCompare ">=1.19.0-0" $root.Capabilities.KubeVersion.GitVersion }}
            securityContext:
              allowPrivilegeEscalation: false
            {{- end }}
            volumeMounts:
            {{- with $dot.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if $dot.nodeSelector }}
          nodeSelector:
            {{- with $dot.nodeSelector }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if $dot.affinity }}
          affinity:
            {{- with $dot.affinity }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if $dot.tolerations }}
          tolerations:
            {{- with $dot.tolerations }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          restartPolicy: {{ default "OnFailure" $dot.restartPolicy }}
          imagePullSecrets:
          - name: {{ include "library.registrySecretName" . }}
          volumes:
          {{ with $dot.volumes }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
status: {}
{{- end }}
{{- end -}}
