{{- if eq ( include "sde.externalDbEnabled" . ) "true" -}}
{{- $sdeDbEnabled := include "sde.dbEnabled" . -}}
{{- if eq $sdeDbEnabled "true" }}
{{- fail "Error: Internal and external db connections enabled" }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database
  labels:
    {{- include "library.labels" . | nindent 4 }}
  {{- if eq ( default false .Values.global.disableHelmHooks ) false }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  {{- end }}
data:
  password: {{ required "Error: External database password is required, '--set external-database.password'" ( index .Values "external-database" "password" ) | b64enc }}
  postgres-password: {{ required "Error: External database password is required, '--set external-database.password'" ( index .Values "external-database" "password" ) | b64enc }}
{{- end -}}