{{- $rwxEnabled := required "For this release, global.rwx.enabled must be set. See https://docs.sdelements.com/release/latest/sysadmin/docs/container/upgrade.html for details." (.Values.global.rwx).enabled -}}
{{- $claimName := printf "%v-%v" ( include "library.trimmedName" . ) "media-volume-claim" -}}
{{- if $rwxEnabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $claimName | quote }}
  labels:
    {{- include "library.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ default "4Gi" .Values.sde.mediaVolumeSize }}
  {{ if .Values.global.storageClass -}}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
status: {}
{{- end }}
