{{- if .Values.global.networkIsolation }}
{{- $releaseName := printf "%v" ( include "library.trimmedName" . ) -}}
{{- $releaseNameShort := printf "%v" ( include "library.trimmedName" . | trunc 10 ) -}}
{{- if eq .Values.global.networkIsolation "namespace" }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $releaseNameShort }}-np-namespace-isolation
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: "{{ $releaseName }}-np-namespace-isolation"
    {{- include "library.labels" $ | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $releaseNameShort }}-np-ingress-nginx-controller
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: "{{ $releaseName }}-np-ingress-nginx-controller"
    {{- include "library.labels" $ | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
      - port: {{ index .Values "ingress-nginx" "controller" "service" "targetPorts" "http" | int | default 80 }}
        protocol: TCP
      - port: {{ index .Values "ingress-nginx" "controller" "service" "targetPorts" "https" | int | default 443 }}
        protocol: TCP
    - from:
      - namespaceSelector:
          matchLabels:
            network.openshift.io/policy-group: monitoring
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: prometheus-stack
        podSelector:
          matchLabels:
            app.kubernetes.io/name: prometheus
      ports:
      - port: 10254
        protocol: TCP

{{- else if eq .Values.global.networkIsolation "ingress" }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $releaseNameShort }}-np-ingress-default-deny
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: "{{ $releaseName }}-np-ingress-default-deny"
    {{- include "library.labels" $ | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
{{- else if eq .Values.global.networkIsolation "full" }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $releaseNameShort }}-np-default-deny
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: "{{ $releaseName }}-np-default-deny"
    {{- include "library.labels" $ | nindent 4 }}
spec:
  podSelector: {}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            k8s-app: kube-dns
    ports:
      - port: 53
        protocol: UDP
  policyTypes:
  - Ingress
  - Egress
{{- end }}
{{- end }}

