{{- $serviceName := printf "%v-%v-%v" ( include "library.trimmedName" . ) "web" "service" -}}
{{- $ingressName := printf "%v-%v-%v" ( include "library.trimmedName" . ) "web" "ingress" -}}
{{- $ingressClassName := default (ternary "public" "openshift-default" (not (.Values.global.openshift).enabled)) .Values.web.ingressClassName -}}
{{- $customCertsProvided := or ( and ( hasKey .Values.web "tlsCertificate" ) ( hasKey .Values.web "tlsKey" )) ( and ( hasKey .Values.web "tlsCertificatePath" ) ( hasKey .Values.web "tlsKeyPath" )) -}}
{{- if or .Values.global.nginxIngress.enabled ( eq ( .Values.global.nginxIngress.enabled | toString ) "<nil>" ) }}
{{- $rootPath := ternary "/" "''" (not (.Values.global.openshift).enabled) }}
{{- $rootPathType := ternary "Prefix" "ImplementationSpecific" (not (.Values.global.openshift).enabled) }}
{{- /* TLS Certificates */ -}}
{{- $externalTlsSecretName := .Values.web.externalTlsSecretName -}}
{{- $customTlsSecretName := printf "%v-tls-web-custom-secret" ( include "library.trimmedName" . ) -}}
{{- $certManagerTlsSecretName := include "tlsSecretName" ( mergeOverwrite $ ( dict "serviceName" "web-server" )) -}}
---
{{- if semverCompare ">=1.19.0-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $ingressName | quote }}
  labels:
    service: {{ $ingressName | quote }}
    {{- include "library.labels" . | nindent 4 }}
  annotations:
    {{- if ((.Values.sde).ingress).annotations -}}
    {{ toYaml .Values.sde.ingress.annotations | nindent 4 }}
    {{- else if  (.Values.global.openshift).enabled }}
    {{- if semverCompare "<1.19.0-0" .Capabilities.KubeVersion.GitVersion }}
    kubernetes.io/ingress.class: {{ $ingressClassName | quote }}
    {{- end }}
    route.openshift.io/termination: "passthrough"
    {{- else }}
    {{- if semverCompare "<1.19.0-0" .Capabilities.KubeVersion.GitVersion }}
    kubernetes.io/ingress.class: {{ $ingressClassName | quote }}
    {{- end }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-body-size: "2048m"
    {{- end }}

spec:
  {{- if semverCompare ">=1.19.0-0" .Capabilities.KubeVersion.GitVersion }}
  ingressClassName: {{ $ingressClassName | quote }}
  defaultBackend:
    service:
      name: {{ $serviceName | quote }}
      port:
        name: "https"
  {{- else }}
  backend:
    serviceName: {{ $serviceName | quote }}
    servicePort: "https"
  {{- end }}
  {{- /* If a domain is set, it must use TLS */ -}}
  {{- if or ( ne .Values.sde.fqdn "example.com" ) ( hasKey .Values.sde "alternateVirtualHosts" ) }}
  tls:
  - hosts:
    - {{ .Values.sde.fqdn | quote }}
    {{- range .Values.sde.alternateDnsNames }}
    - {{ . | quote }}
    {{- end }}
    {{- /*
      * Use external secret name
      * else cert manager secret (if enabled)
      * else custom tls secret
    */ -}}
    {{- if $externalTlsSecretName }}
    secretName: {{ $externalTlsSecretName | quote }}
    {{- else if ( eq ( include "certManagerEnabled" . ) "true" ) }}
    secretName: {{ $certManagerTlsSecretName | quote }}
    {{- else }}
    secretName: {{ $customTlsSecretName | quote }}
    {{- end }}
  {{- if ( hasKey .Values.sde "alternateVirtualHosts" ) }}
  - hosts:
    {{- range .Values.sde.alternateVirtualHosts }}
    - {{ . | quote }}
    {{- end }}
    {{- /* Custom certs take precedence for alternate vhosts so nothing changes for SaaS */ -}}
    {{- if $customCertsProvided }}
    secretName: {{ $customTlsSecretName }}
    {{- else if $externalTlsSecretName }}
    secretName: {{ $externalTlsSecretName | quote }}
    {{- else }}
    secretName: {{ $certManagerTlsSecretName | quote }}
    {{- end }}
  {{- end }}
  {{- if semverCompare ">=1.19.0-0" .Capabilities.KubeVersion.GitVersion }}
  rules:
  - host: {{ .Values.sde.fqdn | quote }}
    http:
      paths:
      - path: {{ $rootPath }}
        pathType: {{ $rootPathType }}
        backend:
          service:
            name: {{ $serviceName | quote }}
            port:
              name: "https"
  {{- range .Values.sde.alternateDnsNames }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: {{ $rootPath }}
        pathType: {{ $rootPathType }}
        backend:
          service:
            name: {{ $serviceName | quote }}
            port:
              name: "https"
  {{- end }}
  {{- range .Values.sde.alternateVirtualHosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: {{ $rootPath }}
        pathType: {{ $rootPathType }}
        backend:
          service:
            name: {{ $serviceName | quote }}
            port:
              name: "https"
  {{- end }}
  {{- else }}
  rules:
  - host: {{ .Values.sde.fqdn | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $serviceName | quote }}
          servicePort: "https"
  {{- range .Values.sde.alternateDnsNames }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $serviceName | quote }}
          servicePort: "https"
  {{- end }}
  {{- range .Values.sde.alternateVirtualHosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $serviceName | quote }}
          servicePort: "https"
  {{- end }}
  {{- end }}
  {{- end }}
status:
  loadBalancer: {}
{{- end -}}
