{{- $mapName := printf "%v-%v" .Release.Name "nginx-resources" -}}
{{- $jittEnabled := default false .Values.sde.enableJITT -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ quote $mapName }}
  labels:
    {{- include "library.labels" . | nindent 4 }}
binaryData:
  {{ range $path, $bytes := .Files.Glob "files-static/custom_status_pages/images/*" }}
    {{ printf "conf/%s:" ( toString $path | trimPrefix "files-static/"  ) |  replace "/" "_" | nindent 2 }} {{ $.Files.Get $path | b64enc }}
  {{ end }}
data:
  {{- range $path, $bytes := .Files.Glob "files-static/custom_status_pages/js/*" -}}
    {{ printf "conf/%s: |" ( toString $path | trimPrefix "files-static/"  ) |  replace "/" "_" | nindent 2 }}
    {{ $.Files.Get $path | nindent 4 }}
  {{- end -}}
  {{- range $path, $bytes := .Files.Glob "files-static/**.html" -}}
    {{ printf "conf/%s: |" ( toString $path | trimPrefix "files-static/"  ) |  replace "/" "_" | nindent 2 }}
    {{ $.Files.Get $path | nindent 4 }}
  {{- end -}}
  {{- range $path, $bytes := .Files.Glob "files-static/**.conf" -}}
    {{- if or (not (contains "jitt" $path)) (and (contains "jitt" $path) $jittEnabled) }}
    {{ printf "conf/%s: |" ( toString $path | trimPrefix "files-static/"  ) |  replace "/" "_" | nindent 2 }}
    {{ $.Files.Get $path | nindent 4 }}
    {{- end }}
  {{- end -}}
