{{- $mapName := printf "%v-%v" .Release.Name "nginx-resources" -}}
{{- $jittEnabled := default false .Values.sde.enableJITT -}}
{{- $403Header := .Values.web.customError.error_403_header | default "<p><strong>403 Forbidden</strong></p>" -}}
{{- $403Body := .Values.web.customError.error_403_body | default "<p>You do not have access to this resource.</p>" -}}
{{- $404Header := .Values.web.customError.error_404_header | default "<p><strong>404 Not Found</strong></p>" -}}
{{- $404Body := .Values.web.customError.error_404_body | default "<p>The server cannot find the requested resource.</p>" -}}
{{- $500Header := .Values.web.customError.error_500_header | default "<p><strong>500 Internal Server Error</strong></p>" -}}
{{- $500Body := .Values.web.customError.error_500_body | default "<p>Well, this is embarrassing. Something went wrong and we don't know how to handle it.</p><br><p>If this error persists, you can report it to site administrators</p>" -}}
{{- $503Header := .Values.web.customError.error_503_header | default "<p><strong>503 Service Unavailable</strong></p>" -}}
{{- $503Body := .Values.web.customError.error_503_body | default "<p>We're probably just performing some maintenance. Please try again shortly.</p><br><p>If this error persists, you can report it to site administrators</p>" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ quote $mapName }}
  labels:
    {{- include "library.labels" . | nindent 4 }}
binaryData:
  {{ range $path, $bytes := .Files.Glob "files-static/custom_status_pages/images/*" }}
    {{ printf "conf/%s:" ( toString $path | trimPrefix "files-static/"  ) |  replace "/" "_" | nindent 2 }} {{ $.Files.Get $path | b64enc }}
  {{ end }}
data:
  NGINX_403_HEADER: {{ $403Header | quote }}
  NGINX_403_BODY: {{ $403Body | quote }}
  NGINX_404_HEADER: {{ $404Header | quote }}
  NGINX_404_BODY: {{ $404Body | quote }}
  NGINX_500_HEADER: {{ $500Header | quote }}
  NGINX_500_BODY: {{ $500Body | quote }}
  NGINX_503_HEADER: {{ $503Header | quote }}
  NGINX_503_BODY: {{ $503Body | quote }}
  {{- range $path, $bytes := .Files.Glob "files-static/custom_status_pages/js/*" -}}
    {{ printf "conf/%s: |" ( toString $path | trimPrefix "files-static/"  ) |  replace "/" "_" | nindent 2 }}
    {{ $.Files.Get $path | nindent 4 }}
  {{- end -}}
  {{- range $path, $bytes := .Files.Glob "files-static/**.html" -}}
    {{ printf "conf/%s: |" ( toString $path | trimPrefix "files-static/"  ) |  replace "/" "_" | nindent 2 }}
    {{ $.Files.Get $path | nindent 4 }}
  {{- end -}}
  {{- range $path, $bytes := .Files.Glob "files-static/**.conf" -}}
    {{- if or (not (contains "jitt" $path)) (and (contains "jitt" $path) $jittEnabled) }}
    {{ printf "conf/%s: |" ( toString $path | trimPrefix "files-static/"  ) |  replace "/" "_" | nindent 2 }}
    {{ $.Files.Get $path | nindent 4 }}
    {{- end }}
  {{- end -}}
