{{- if .Values.postgresql.pdb.create }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "library.trimmedName" . }}-database
  labels:
    {{- include "library.labels" . | nindent 4 }}
spec:
  {{- if .Values.postgresql.pdb.minAvailable }}
  minAvailable: {{ .Values.postgresql.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.postgresql.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.postgresql.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "library.trimmedName" . }}
      name: {{ include "library.trimmedName" . }}-database
{{- end }}