{{- $imageTag := default ( default .Chart.AppVersion .Values.global.imageTag ) .Values.mail.imageTag | toString -}}
{{- $imagePullPolicy := default .Values.global.imagePullPolicy .Values.mail.imagePullPolicy -}}
{{- $imageRegistry := required "An image registry needs to be specified in your configuration values!" ( default .Values.global.imageRegistry .Values.mail.imageRegistry ) -}}
{{- $imageOrganization := required "An image organization needs to be specified in your configuration values!" ( default .Values.global.imageOrganization .Values.mail.imageOrganization ) -}}
{{- $imageName := default "postfix" .Values.mail.imageName -}}
{{- $imageSource := hasKey .Values.mail "imageSource" | ternary ( printf "%s" .Values.mail.imageSource ) ( default "3rd" .Values.global.imageSource ) -}}
{{- $imageRegistryFormat := default "%s/%s-%s-%s:%s" .Values.global.imageRegistryFormat -}}
{{- $deploymentName := printf "%v-%v" ( include "library.trimmedName" . ) "mail" -}}
{{- $serviceName := printf "%v-%v-%v" ( include "library.trimmedName" . ) "mail" "service" -}}
{{- $port := default 25 .Values.mail.port -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName | quote }}
  labels:
    name: {{ $deploymentName | quote }}
    {{- include "library.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.mail.replicas }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      name: {{ $deploymentName | quote }}
      {{- include "library.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      labels:
        name: {{ $deploymentName | quote }}
        {{- include "library.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.global.enableNodeSelector }}
      nodeSelector:
        customer_name: {{ printf "%v" .Release.Name | quote }}
      {{- end }}
      containers:
      - name: {{ $deploymentName | quote }}
        image: {{ printf $imageRegistryFormat $imageRegistry $imageOrganization $imageSource $imageName $imageTag | quote }}
        imagePullPolicy: {{ $imagePullPolicy }}
        env:
        - name: POSTFIX_MYNETWORKS
          value: {{ default "127.0.0.1/32 10.0.0.0/8 172.16.0.0/12 192.168.100.0/16" .Values.mail.appovedNetworks | quote }}
        {{- if .Values.mail.relayHost }}
        - name: POSTFIX_RELAYHOST
          value: {{ .Values.mail.relayHost | quote }}
        {{- if .Values.mail.relayHostPort }}
        - name: POSTFIX_RELAYHOST_PORT
          value: {{ .Values.mail.relayHostPort | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.mail.resources }}
        resources:
        {{- range $limitType, $resources := $.Values.mail.resources }}
            {{ $limitType }}:
            {{- range $resourceKey, $resourceValue := $resources }}
                {{ $resourceKey }}: {{ $resourceValue }}
            {{- end }}
        {{- end }}
        {{- else }}
        resources: {}
        {{- end }}
      imagePullSecrets:
      - name: security-compass-secret
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName | quote }}
  labels:
    service: {{ $serviceName | quote }}
    {{- include "library.labels" . | nindent 4 }}
spec:
  ports:
  - name: {{ printf "%d" $port | quote }}
    port: {{ $port }}
    targetPort: {{ $port }}
  selector:
    name: {{ $deploymentName | quote }}
status:
  loadBalancer: {}
