{{- $imagePullPolicy := default .Values.global.imagePullPolicy .Values.datastore.imagePullPolicy -}}
{{- $imageRegistryFormat := default "%s/%s-%s-%s:%s" .Values.global.imageRegistryFormat -}}
{{- $imageRegistry := required "An image registry needs to be specified in your configuration values!" ( default .Values.global.imageRegistry .Values.datastore.imageRegistry ) -}}
{{- $imageOrganization := required "An image organization needs to be specified in your configuration values!" ( default .Values.global.imageOrganization .Values.datastore.imageOrganization ) -}}
{{- $imageSource := default ( default "3rd" .Values.global.imageSource ) .Values.datastore.imageSource -}}
{{- $imageName := default "redis" .Values.datastore.imageName -}}
{{- $imageTag := default ( default .Chart.AppVersion .Values.global.imageTag ) .Values.datastore.imageTag | toString -}}
{{- $uid := default 999 .Values.datastore.uid -}}
{{- $gid := default 1000 .Values.datastore.gid -}}
{{- $fsgid := default 1000 .Values.datastore.fsgid -}}
{{- $deploymentName := printf "%v-%v" ( include "library.trimmedName" . ) "datastore" -}}
{{- $serviceName := printf "%v-%v-%v" ( include "library.trimmedName" . ) "datastore" "service" -}}
{{- $port := include "datastore.port" . -}}
{{- $dataMountPoint := default "/data" .Values.datastore.dataMountPoint -}}
{{- $dataClaimName := printf "%v-%v" ( include "library.trimmedName" . ) "datastore-volume-claim" -}}
{{- $secretName := printf "%v-%v" .Release.Name "sde-secrets" -}}
{{- $mapName := printf "%v-%v" .Release.Name "redis-resources" -}}

{{/* TLS variables */}}
{{- $tlsRoot := default "/tls" .Values.datastore.tlsRoot -}}
{{- $tlsCACertPath := printf "%v/%v" $tlsRoot "ca.crt" }}
{{- $tlsCertPath := printf "%v/%v" $tlsRoot "tls.crt" }}
{{- $tlsKeyPath := printf "%v/%v" $tlsRoot "tls.key" }}

{{- $enableInternalTls := eq ( include "enableInternalTls" . ) "true" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName | quote }}
  labels:
    name: {{ $deploymentName | quote }}
    {{- include "library.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.datastore.replicas }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      name: {{ $deploymentName | quote }}
      {{- include "library.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ $deploymentName | quote }}
        {{- include "library.selectorLabels" . | nindent 8 }}
    spec:
      {{- if not ((.Values.global.openshift).enabled) }}
      securityContext:
        {{- if not .Values.global.runAsRoot }}
        runAsUser: {{ $uid }}
        runAsGroup: {{ $gid }}
        fsGroup: {{ $fsgid }}
        {{- if semverCompare ">=1.23.0-0" .Capabilities.KubeVersion.GitVersion }}
        fsGroupChangePolicy: "OnRootMismatch"
        {{- end }}
        {{- else }}
        runAsUser: 0
        runAsGroup: 0
        {{- end }}
      {{- end }}
      {{- if .Values.global.enableNodeSelector }}
      nodeSelector:
        customer_name: {{ printf "%v" .Release.Name | quote }}
      {{- end }}
      containers:
      - name: {{ $deploymentName | quote }}
        image: {{ printf $imageRegistryFormat $imageRegistry $imageOrganization $imageSource $imageName $imageTag | quote }}
        imagePullPolicy: {{ $imagePullPolicy }}
        args:  # Override in command line
        - "/usr/local/etc/redis/redis.conf"
        - "--requirepass"
        - "$(REDIS_PASSWORD)"
        {{- if $enableInternalTls }}
        - "--tls-cert-file"
        - "{{ $tlsCertPath }}"
        - "--tls-key-file"
        - "{{ $tlsKeyPath }}"
        - "--tls-ca-cert-file"
        - "{{ $tlsCACertPath }}"
        - "--port 0"
        - "--tls-port 6379"
        - "--tls-auth-clients optional"
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: REDIS_DB
          value: {{ hasKey .Values.datastore "databaseName" | ternary .Values.datastore.databaseName (default ( printf "sde_%s" .Chart.AppVersion ) .Values.sde.databasePrefix) | quote }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ $secretName | quote }}
              key: SDE_DATASTORE_PASSWORD
        {{ if (.Values.global.openshift).enabled -}}
        - name: SDE_OPENSHIFT_ENABLED
          value: "true"
        {{ end -}}
        ports:
        - containerPort: {{ int $port }}
        {{- if .Values.datastore.resources }}
        resources:
        {{- range $limitType, $resources := $.Values.datastore.resources }}
            {{ $limitType }}:
            {{- range $resourceKey, $resourceValue := $resources }}
                {{ $resourceKey }}: {{ $resourceValue }}
            {{- end }}
        {{- end }}
        {{- else }}
        resources: {}
        {{- end }}
        volumeMounts:
        - mountPath: {{ $dataMountPoint | quote }}
          name: datastore
        - mountPath: /usr/local/etc/redis/  # redis.conf
          name: redis-config
          readOnly: true
        {{- if $enableInternalTls }}
        - mountPath: {{ $tlsRoot }}
          name: tls
          readOnly: true
        {{- end }}
      imagePullSecrets:
      - name: security-compass-secret
      restartPolicy: Always
      volumes:
      - name: datastore
        persistentVolumeClaim:
          claimName: {{ $dataClaimName | quote }}
      - name: redis-config
        configMap:
          name: {{ $mapName | quote }}
          items:
          {{- range $path, $bytes := .Files.Glob "files-datastore/*.conf" }}
          - key: {{ printf "conf/%s" ( toString $path | trimPrefix "files-datastore/"  ) | replace "/" "_" }}
            path: {{ toString $path | trimPrefix "files-datastore/" | quote }}
          {{- end }}
      {{- if $enableInternalTls }}
      - name: tls
        secret:
          secretName: {{ include "tlsSecretName" ( mergeOverwrite . ( dict "serviceName" "datastore-server" ) ) }}
          defaultMode: 0400
      {{- end }}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName | quote }}
  labels:
    service: {{ $serviceName | quote }}
    {{- include "library.labels" . | nindent 4 }}
spec:
  ports:
  - name: {{ $port | quote }}
    port: {{ int $port }}
    targetPort: {{ int $port }}
  selector:
    name: {{ $deploymentName | quote }}
status:
  loadBalancer: {}
{{ $ca := genCA "datastore-ca" 3650 }}
{{ dict "root" . "serviceName" "datastore-server" "ca" $ca | include "sde.certs" }}
{{ dict "root" . "serviceName" "datastore-client" "ca" $ca | include "sde.certs" }}
