{{- $mapName := printf "%v-%v" .Release.Name "reporting-resources" -}}
{{- $reportingEnabled := include "reportingEnabled" . -}}

{{- if eq $reportingEnabled "true" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ quote $mapName }}
  labels:
    {{- include "library.labels" . | nindent 4 }}
data:
  {{- range $path, $bytes := .Files.Glob "files-reporting/**.conf" -}}
    {{ printf "conf/%s: |" ( toString $path | trimPrefix "files-reporting/"  ) |  replace "/" "_" | nindent 2 }}
    {{ $.Files.Get $path | nindent 4 }}
  {{- end -}}
{{- end }}
