{{- if eq .Values.global.registrySecretName "security-compass-secret" }}
{{- $disableHelmHooks := default false .Values.global.disableHelmHooks -}}
{{- $registryUsername := required "Container registry username is required, e.g. '--set global.imageRegistryUsername=...' or in values.yaml" .Values.global.imageRegistryUsername -}}
{{- $registryPassword := required "Container regestry password is required, e.g. '--set global.imageRegistryPassword=...' or in values.yaml" .Values.global.imageRegistryPassword -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: security-compass-secret
  labels:
    {{- include "library.labels" . | nindent 4 }}
  {{- if eq $disableHelmHooks false }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ tpl (.Files.Get "conf/registry-secrets.json") . | b64enc  }}
{{- end }}
