{{- if not .Values.global.secretName -}}
{{- $sdeDbEnabled := include "sde.dbEnabled" . -}}
{{- $externalDbEnabled := include "sde.externalDbEnabled" . -}}
{{- $dbPassword := include "sde.dbPassword" . -}}
{{- if and (eq $sdeDbEnabled "true") (eq $externalDbEnabled "true") }}
{{- fail "Error: Internal and external db connections enabled" }}
{{- end }}
{{- $githubClient := index .Values.sde.codeScanning "github" "client" -}}
{{- $githubSecret := index .Values.sde.codeScanning "github" "secret" -}}
{{- $gitlabClient := index .Values.sde.codeScanning "gitlab" "client" -}}
{{- $gitlabSecret := index .Values.sde.codeScanning "gitlab" "secret" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sde-secrets
  labels:
    {{- include "library.labels" . | nindent 4 }}
  {{- if eq ( default false .Values.global.disableHelmHooks ) false }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  {{- end }}
data:
  {{- if eq $sdeDbEnabled "true"}}
  SDE_DATABASE_PASSWORD: {{ required "Error: SDE database password is required, '--set postgresql.auth.password'" $dbPassword | b64enc }}
  {{- end }}
  {{- if eq $externalDbEnabled "true"}}
  SDE_DATABASE_PASSWORD: {{ required "Error: External database password is required, '--set external-database.password'" ( index .Values "external-database" "password" ) | b64enc }}
  {{- end }}
  SDE_DATASTORE_PASSWORD: {{ required "Error: SDE datastore password is required, '--set sc-datastore.clientPassword'" ( index .Values "sc-datastore" "clientPassword" ) | b64enc}}
  SDE_JWT_SECRET: {{ required "SDE JWT secret is required, '--set sde.jwtSecret'" .Values.sde.jwtSecret | b64enc}}
  SDE_SECRET_KEY: {{ required "SDE secret key is required, '--set sde.secretKey'" .Values.sde.secretKey | b64enc}}
  SDE_SUPERUSER_PASSWORD: {{ required "SDE superuser password is required, '--set sde.superuserPassword'" .Values.sde.superuserPassword | b64enc }}
  SDE_CACHES: {{ tpl (.Files.Get "conf/caches.json") . | b64enc }}
  {{ if .Values.global.sharedStorage }}
  S3_ACCESS_KEY: {{ required "global.sharedStorage.s3AccessKey is required" .Values.global.sharedStorage.s3AccessKey | b64enc }}
  S3_SECRET_KEY: {{ required "global.sharedStorage.s3SecretKey is required" .Values.global.sharedStorage.s3SecretKey | b64enc }}
  {{- end }}
  {{- if and $githubClient $githubSecret }}
  SDE_GITHUB_OAUTH_CLIENT_ID: {{ $githubClient | b64enc }}
  SDE_GITHUB_OAUTH_SECRET: {{ $githubSecret | b64enc }}
  {{- end }}
  {{- if and $gitlabClient $gitlabSecret }}
  SDE_GITLAB_OAUTH_CLIENT_ID: {{ $gitlabClient | b64enc }}
  SDE_GITLAB_OAUTH_SECRET: {{ $gitlabSecret | b64enc }}
  {{- end }}
{{- end -}}
