{{- if not .Values.global.secretName -}}
{{- $sdeDbEnabled := include "sde.dbEnabled" . -}}
{{- $externalDbEnabled := include "sde.externalDbEnabled" . -}}
{{- if and (eq $sdeDbEnabled "true") (eq $externalDbEnabled "true") }}
{{- fail "Error: Internal and extranal db connections enabled" }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sde-secrets
  labels:
    {{- include "library.labels" . | nindent 4 }}
  {{- if eq ( default false .Values.global.disableHelmHooks ) false }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  {{- end }}
data:
  {{- if eq $sdeDbEnabled "true"}}
  SDE_DATABASE_PASSWORD: {{ required "Error: SDE database password is required, '--set sc-database.clientPassword'" ( index .Values "sc-database" "clientPassword" ) | b64enc }}
  {{- end }}
  {{- if eq $externalDbEnabled "true"}}
  SDE_DATABASE_PASSWORD: {{ required "Error: External database password is required, '--set external-database.password'" ( index .Values "external-database" "password" ) | b64enc }}
  {{- end }}
  SDE_DATASTORE_PASSWORD: {{ required "SDE datastore password is required, '--set datastore.clientPassword'" .Values.datastore.clientPassword  | b64enc}}
  SDE_JWT_SECRET: {{ required "SDE JWT secret is required, '--set sde.jwtSecret'" .Values.sde.jwtSecret | b64enc}}
  SDE_SECRET_KEY: {{ required "SDE secret key is required, '--set sde.secretKey'" .Values.sde.secretKey | b64enc}}
  SDE_SUPERUSER_PASSWORD: {{ required "SDE superuser password is required, '--set sde.superuserPassword'" .Values.sde.superuserPassword | b64enc }}
  SDE_CACHES: {{ tpl (.Files.Get "conf/caches.json") . | b64enc }}
  {{ if .Values.global.sharedStorage }}
  {{- if eq ( upper .Values.global.sharedStorage.storageType ) "S3" }}
  S3_ACCESS_KEY: {{ required "global.sharedStorage.s3AccessKey is required when s3 storage is being used" .Values.global.sharedStorage.s3AccessKey | b64enc }}
  S3_SECRET_KEY: {{ required "global.sharedStorage.s3SecretKey is required when s3 storage is being used" .Values.global.sharedStorage.s3SecretKey | b64enc }}
  {{- end }}
  {{- end }}
{{- end -}}
