{{- $root := . -}}
{{- $imagePullPolicy := default .Values.global.imagePullPolicy .Values.reporting.imagePullPolicy -}}
{{- $imageRegistryFormat := default "%s/%s-%s-%s:%s" .Values.global.imageRegistryFormat -}}
{{- $imageRegistry := required "An image registry needs to be specified in your configuration values!" ( default .Values.global.imageRegistry .Values.reporting.imageRegistry ) -}}
{{- $imageOrganization := required "An image organization needs to be specified in your configuration values!" ( default .Values.global.imageOrganization .Values.reporting.imageOrganization ) -}}
{{- $imageSource := hasKey .Values.reporting "imageSource" | ternary ( printf "%s" .Values.reporting.imageSource ) ( default "sde" .Values.global.imageSource ) -}}
{{- $imageName := default "web-reporting" .Values.reporting.imageName -}}
{{- $imageTag := default ( default .Chart.AppVersion .Values.global.imageTag ) .Values.reporting.imageTag | toString -}}
{{- $nginxImageOrganization := required "An image organization needs to be specified in your configuration values!" ( default $imageOrganization .Values.web.imageOrganization ) -}}
{{- $nginxImageSource := default $imageSource .Values.web.imageSource -}}
{{- $nginxImageName := default "web-static" .Values.web.imageName -}}
{{- $nginxImageTag := default $imageTag ( default .Values.web.imageTag .Values.reporting.nginxImageTag ) | toString -}}
{{- $fsgid := default 33 .Values.reporting.fsgid -}}
{{- $uid := default 1000 .Values.reporting.uid -}}
{{- $gid := default 1000 .Values.reporting.gid -}}
{{- $nginxuid := default 101 .Values.reporting.nginxuid -}}
{{- $nginxgid := default 101 .Values.reporting.nginxgid -}}
{{- $deploymentName := printf "%v-%v" ( include "library.trimmedName" . ) "reporting" -}}
{{- $serviceName := printf "%v-%v-%v" ( include "library.trimmedName" . ) "reporting" "service" -}}
{{- $tlsRoot := default "/tls" .Values.reporting.tlsRoot -}}
{{- $tlsCertPath := printf "%v/tls.crt" $tlsRoot }}
{{- $tlsKeyPath := printf "%v/tls.key" $tlsRoot }}
{{- $mapName := printf "%v-%v" .Release.Name "reporting-resources" -}}
{{- $reportingEnabled := include "reportingEnabled" . -}}
{{- $reportingPort := include "reportingPort" . -}}
{{- $cubejsPort := default 2823 .Values.reporting.cubejsPort -}}
{{- $certManagerEnabled := eq ( include "certManagerEnabled" . ) "true" -}}
{{- $enableInternalTls := eq ( include "enableInternalTls" . ) "true" -}}
{{- $ipFamilies := default (list "IPv4") .Values.global.ipFamilies -}}
{{/* featureFlag */}}
{{- $sentryEnabled := default false (eq (($root.Values.reporting.sentry).enabled | toString) "<nil>" | ternary ($root.Values.global.sentry).enabled ($root.Values.reporting.sentry).enabled) -}}

{{/* Env vars */}}
{{- $secretName := printf "%v-%v" .Release.Name "sde-secrets" -}}
{{- $dbServiceName := printf "%v-database" ( include "library.trimmedName" $root ) -}}
{{- $redisUrl := printf "redis://%v-datastore-service:%v" ( include "library.trimmedName" . ) ( include "sde.datastorePort" . ) -}}
{{- $cacheQueueServiceName := printf "%v-%v-%v" ( include "library.trimmedName" . ) "cache-queue" "service" -}}
{{- $version := semver $root.Chart.Version -}}
{{- $sdeReleaseName := default ( printf "sde@%v.%v" $version.Major $version.Minor ) (default ($root.Values.global.sentry).releaseName ($root.Values.worker.sentry).releaseName) -}}
{{- $sdeWorkerScheme := ternary "https" "http" $enableInternalTls -}}
{{- $sdeWorkerPort := default 8080 .Values.worker.synchronous.highPriority.port -}}
{{- $sdeWorker := printf "worker-%v" .Values.worker.synchronous.highPriority.niceness }}
{{- $sdeUrl := printf "%v://%v-%v-%v:%v" $sdeWorkerScheme ( include "library.trimmedName" . ) $sdeWorker "service" $sdeWorkerPort -}}

{{/* Sentry variables */}}
{{- $sentryDSN := ($root.Values.reporting.sentry).dsn }}
{{- $sentryEnvironment := default $root.Release.Namespace (default ($root.Values.global.sentry).environment ($root.Values.reporting.sentry).environment) }}
{{- $sentrySampleRate := default 0.1 (default ($root.Values.global.sentry).sampleRate ($root.Values.reporting.sentry).sampleRate) }}
{{- $sentryTraceSampleRate := default 0.1 (default ($root.Values.global.sentry).traceSampleRate ($root.Values.reporting.sentry).traceSampleRate) }}

{{/* Sanity Check */}}
{{- if eq (int $reportingPort) (int $cubejsPort) -}}
{{- fail "Reporting port and CubeJS port cannot be the same due to port conflicts." }}
{{- end -}}

{{- $updateStrategy := default "RollingUpdate" (index $root.Values.reporting "updateStrategy").type }}
{{- if eq $reportingEnabled "true" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName | quote }}
  labels:
    name: {{ $deploymentName | quote }}
    {{- include "library.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.reporting.replicas }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      name: {{ $deploymentName | quote }}
      {{- include "library.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ $updateStrategy }}
  template:
    metadata:
      labels:
        name: {{ $deploymentName | quote }}
        {{- include "library.selectorLabels" . | nindent 8 }}
    spec:
      {{- if not ((.Values.global.openshift).enabled) }}
      securityContext:
        {{- if not .Values.global.runAsRoot }}
        runAsUser: {{ $uid }}
        runAsGroup: {{ $gid }}
        fsGroup: {{ $fsgid }}
        {{- if semverCompare ">=1.23.0-0" .Capabilities.KubeVersion.GitVersion }}
        fsGroupChangePolicy: "OnRootMismatch"
        {{- end }}
        {{- else }}
        runAsUser: 0
        runAsGroup: 0
        {{- end }}
      {{- end }}
      {{- if .Values.global.enableNodeSelector }}
      nodeSelector:
        customer_name: {{ printf "%v" ( include "library.trimmedName" . ) | quote }}
      {{- end }}
      containers:
      - name: {{ printf "%s-nginx" $deploymentName | quote }}
        image: {{ printf $imageRegistryFormat $imageRegistry $nginxImageOrganization $nginxImageSource $nginxImageName $nginxImageTag | quote }}
        imagePullPolicy: {{ $imagePullPolicy }}
        args:
        - /bin/bash
        - -c
        - /bin/run_nginx.sh
        env:
        - name: REPORTING_PORT
          value: {{ $reportingPort | quote }}
        - name: CUBEJS_PORT
          value: {{ $cubejsPort | quote }}
        {{- if $enableInternalTls }}
        - name: LISTEN_SUFFIX
          value: "default ssl"
        - name: NGINX_SSL_INCLUDE_CONF
          value: "include /etc/nginx/reporting-tls.conf;"
        - name: CUBEJS_TLS_PRIVATE_KEY_FILE
          value: {{ $tlsKeyPath | quote }}
        - name: CUBEJS_TLS_PRIVATE_FULLCHAIN_FILE
          value: {{ $tlsCertPath | quote }}
        - name: NGINX_SSL_CIPHERS
          value: {{ default "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256" .Values.reporting.tlsCiphers | quote}}
        - name: NGINX_SSL_PROTOCOLS
          value: {{ default "TLSv1 TLSv1.1 TLSv1.2" .Values.reporting.tlsProtocols | quote }}
        {{ else }}
        - name: LISTEN_SUFFIX
          value: "default"
        - name: NGINX_SSL_INCLUDE_CONF
          value: ""
        {{- end }}
        - name: NGINX_WORKER_PROCESSES
          value: {{ default "2" .Values.reporting.workerProcesses | quote }}
        - name: NGINX_WORKER_RLIMIT_NOFILE
          value: {{ default 1024 .Values.reporting.rlimitNofile | quote }}
        - name: NGINX_WORKER_CONNECTIONS
          value: {{ default 1024 .Values.reporting.workerConnections | quote }}
        {{- if (.Values.global.openshift).enabled }}
        - name: SDE_OPENSHIFT_ENABLED
          value: "true"
        {{- end }}
        ports:
        - containerPort: {{ int $reportingPort }}
        volumeMounts:
        - mountPath: /run/nginx
          name: reporting-nginx
          readOnly: true
        {{- if $enableInternalTls }}
        - name: tls
          mountPath: {{ $tlsRoot }}
          readOnly: true
        {{- end }}
        {{- if not ((.Values.global.openshift).enabled) }}
        securityContext:
          {{- if not .Values.global.runAsRoot }}
          runAsUser: {{ $nginxuid }}
          runAsGroup: {{ $nginxgid }}
          {{- else }}
          runAsUser: 0
          runAsGroup: 0
          {{- end }}
        {{- end }}
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 5; /usr/sbin/nginx -s quit; while pgrep -x nginx; do sleep 1; done"]
      - name: {{ $deploymentName | quote }}
        image: {{ printf $imageRegistryFormat $imageRegistry $imageOrganization $imageSource $imageName $imageTag | quote }}
        imagePullPolicy: {{ $imagePullPolicy }}
        args:
        - yarn
        - start
        securityContext:
          allowPrivilegeEscalation: false
        env:
        {{- range .Values.reporting.extraEnvVars }}
        - name: {{ .name | quote }}
          value: {{ .value | quote }}
        {{- end }}
        - name: SDE_URL
          value: {{ $sdeUrl | quote }}
        - name: SDE_RELEASE
          value: {{ $sdeReleaseName | quote }}
        # https://cube.dev/docs/@cubejs-backend-server#api-reference-this-listen-options
        - name: PORT
          value: {{ $cubejsPort | quote }}
        - name: CUBEJS_WEB_SOCKETS
          value: {{ default "true" .Values.reporting.webSockets | quote }}
        - name: CUBEJS_DB_TYPE
          value: {{ default "postgres" .Values.reporting.dbType | quote }}
        - name: CUBEJS_CACHE_AND_QUEUE_DRIVER
          value: {{ default "redis" .Values.reporting.datastoreDriver | quote }}
        - name: CUBEJS_DB_HOST
          value: {{ include "sde.dbHost" . | quote }}
        - name: CUBEJS_DB_PORT
          value: {{ include "sde.dbPort" . | quote }}
        - name: CUBEJS_DB_NAME
          value: {{ include "sde.dbName" . | quote }}
        - name: CUBEJS_DB_USER
          value: {{ include "sde.dbUser" . | quote }}
        - name: CUBEJS_SCHEDULED_REFRESH_TIMER
          value: "true"
        - name: CUBEJS_DB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ $secretName | quote }}
              key: SDE_DATABASE_PASSWORD
        - name: CUBEJS_API_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ $secretName | quote }}
              key: SDE_JWT_SECRET
        # Production mode requires enabling security: https://cube.dev/docs/deployment#production-mode-redis
        - name: NODE_ENV
          value: production
        - name: REDIS_TLS
          value: "false"
        - name: REDIS_URL
          value: {{ $redisUrl | quote }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ $secretName | quote }}
              key: SDE_DATASTORE_PASSWORD
        - name: NODE_TLS_REJECT_UNAUTHORIZED # Ignore self-signed certs
          value: {{ default "0" .Values.reporting.nodeTlsRejectUnauthorized | quote }}
        {{- if (.Values.global.openshift).enabled }}
        - name: SDE_OPENSHIFT_ENABLED
          value: "true"
        {{- end }}
        {{- if $sentryEnabled }}
        - name: SDE_REPORTING_SENTRY_DSN
          value: {{ required "SDE_REPORTING_SENTRY_DSN must be specified if Sentry configuration is enabled." $sentryDSN | quote }}
        - name: SDE_SENTRY_ENVIRONMENT
          value: {{ $sentryEnvironment | quote }}
        - name: SDE_SENTRY_SAMPLE_RATE
          value: {{ $sentrySampleRate | quote }}
        - name: SDE_SENTRY_TRACE_SAMPLE_RATE
          value: {{ $sentryTraceSampleRate | quote }}
        {{- end }}
        {{- if or (.Values.reporting.preAggregations) (eq (.Values.reporting.preAggregations | toString) "<nil>") }}
        - name: ENABLE_PREAGGREGATIONS
          value: "true"
        {{- else }}
        - name: ENABLE_PREAGGREGATIONS
          value: "false"
        {{- end }}
        - name: ENABLE_ADVANCED_REPORTING_TREND_REPORTS
        {{/* If variable is true or unset, set to "true" */}}
        {{- if or (.Values.reporting.enableAdvancedTrendReports) (eq (.Values.reporting.enableAdvancedTrendReports | toString) "<nil>") }}
          value: "true"
        {{- else }}
          value: "false"
        {{- end }}
        {{- if (.Values.reporting.taskRiskRelevancePreAggregationInterval) }}
        - name: TASK_RISK_RELEVANCE_PREAGGREGATION_INTERVAL
          value: {{ .Values.reporting.taskRiskRelevancePreAggregationInterval | quote }}
        {{- end }}
        - name: IP_FAMILY
          value: {{ ternary "IPv6" "IPv4" (has "IPv6" $ipFamilies) | quote }}
        {{- if .Values.reporting.resources }}
        resources:
        {{- range $limitType, $resources := $.Values.reporting.resources }}
            {{ $limitType }}:
            {{- range $resourceKey, $resourceValue := $resources }}
                {{ $resourceKey }}: {{ $resourceValue }}
            {{- end }}
        {{- end }}
        {{- else }}
        resources: {}
        {{- end }}
      imagePullSecrets:
      - name: {{ include "library.registrySecretName" . }}
      restartPolicy: Always
      terminationGracePeriodSeconds: {{ default 30 $root.Values.reporting.terminationGracePeriodSeconds }}
      volumes:
      - name: reporting-nginx
        configMap:
          name: {{ $mapName | quote }}
          items:
          {{- range $path, $bytes := .Files.Glob "files-reporting/**.conf" }}
          - key: {{ printf "conf/%s" ( toString $path | trimPrefix "files-reporting/"  ) | replace "/" "_" }}
            path: {{ toString $path | trimPrefix "files-reporting/" | quote }}
          {{- end }}
      {{- if $enableInternalTls }}
      - name: tls
        secret:
          secretName: {{ include "tlsSecretName" ( mergeOverwrite . (dict "serviceName" "reporting-server")) | quote }}
          defaultMode: 0400
      {{- end }}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName | quote }}
  labels:
    service: {{ $serviceName | quote }}
    {{- include "library.labels" . | nindent 4 }}
spec:
  ipFamilies:
  {{- $ipFamilies | toYaml | trim | nindent 2 }}
  ipFamilyPolicy: {{ ternary "PreferDualStack" "SingleStack" (gt (len $ipFamilies) 1) }}
  ports:
  - name: "port"
    port: {{ int $reportingPort }}
    targetPort: {{ int $reportingPort }}
  selector:
    name: {{ $deploymentName | quote }}
status:
  loadBalancer: {}

{{ dict "root" $root "serviceName" "reporting-server" "commonName" $serviceName | include "sde.certs" }}
{{- end -}}
