{{- $serviceName := printf "%v-%v-%v" ( include "library.trimmedName" . ) "broker" "service" -}}
{{- $deploymentName := printf "%v-%v" ( include "library.trimmedName" . ) "broker" -}}
{{- $port := default 5672 .Values.port -}}
{{- $ipFamilies := default (list "IPv4") .Values.global.ipFamilies -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName | quote }}
  labels:
    service: {{ $serviceName | quote }}
    {{- include "library.labels" . | nindent 4 }}
spec:
  ipFamilies:
  {{- $ipFamilies | toYaml | trim | nindent 2 }}
  ipFamilyPolicy: {{ ternary "PreferDualStack" "SingleStack" (gt (len $ipFamilies) 1) }}
  ports:
  - name: {{ printf "%d" $port | quote }}
    port: {{ $port }}
    targetPort: {{ $port }}
  - name: "15672"
    port: 15672
    targetPort: 15672
  selector:
    name: {{ $deploymentName | quote }}
status:
  loadBalancer: {}
