apiVersion: v2
appVersion: 1.5.2
dependencies:
- name: sc-library
  repository: https://harbor-dev.sdelements.com/chartrepo/library
  version: 0.1.1
- condition: useBrokerSubchart
  name: sc-broker
  repository: https://harbor-dev.sdelements.com/chartrepo/library
  version: 1.2.1
- condition: minio.enabled
  name: minio
  repository: https://charts.min.io/
  version: 3.4.6
description: SD Elements PAS Plugin Worker Service
home: https://docker.sdelements.com
icon: https://avatars0.githubusercontent.com/u/739346
keywords:
- sde
- sdelements
- pas
- celery
- python
maintainers:
- email: devops-support@securitycompass.com
  name: Security Compass Technologies Ltd.
  url: https://www.securitycompass.com/
name: pas-plugin-worker
sources:
- https://agra.sdelements.com/sd-elements/management_command_system
type: application
version: 1.5.2
