### Default values for the SDE Worker Helm Chart.
### This is a YAML-formatted file.
### Declare variables to be passed into your templates.

## Options & settings accessible by all charts
global:
  ## Provide a name in place of `sde` for `app:` labels
  ##
  #nameOverride: ""

  ## Provide a name to substitute for the full names of resources
  ##
  #fullnameOverride: ""

  ## Configuration options and crentials to fetch images from private
  ## registries/repositories. These are provided by SDElements support staff on
  ## request upon purchase of the SDElements product.
  ##
  imageRegistry: docker.sdelements.com
  #imageRegistry: docker-dev.sdelements.com

  # Format: $imageRegistry $imageOrganization $imageSource $imageName $imageTag
  # docker.sdelements.com / default_organization - (sde/3rd) - cert-creator : latest
  # docker-dev.sdelements.com / dev _ (sde/3rd) / cert-creator : latest
  #imageRegistryFormat: "%s/%s_%s/%s:%s"
  imageRegistryFormat: "%s/%s-%s-%s:%s"
  imageRegistryUsername: acmecorp
  imageRegistryPassword: SuperSecretPassword
  imageOrganization: default_organization
  #imageOrganization: dev
  imagePullPolicy: IfNotPresent
  #imageSource: sde
  #
  # Fully Qualified Domain Name(s)
  #
  # fqdn: example.com
  # DNS Aliases & Extra names
  # FQDN and alternateDnsNames are used to create DNS records and
  # get certificates issued dynamically.
  # Connections to URLs defined in these are encrypted by default using Cert Manager
  # and if not defined will fall back to Custom Certs/self-signed Certs.
  # alternateDnsNames:
  #  - alias.example.com
  #  - othername.example.com
  # alternateVirtualHosts are used to create config sections in the ingress and
  # can be optionally used with a custom cert.
  # When custom certs are configured any connections to these URLs will be encrypted using said certs,
  # in case custom certs are not configured the ingress will back to using self signed certs.
  # alternateVirtualHosts:
  #  - externally-managed-dns-record.example.com

  ## Feature flags that enable/disable subcharts and subchart features
  # that need to be specified before runtime because they affect how subcharts
  # deploy themselves
  #

  pas:
    #pluginServiceQueueName: plugin_service_worker
    # Global PAS broker config
    broker: {}
      ## Username for broker user
      #user: pas
      #password:
      #secretName:
      #passwordSecretKey:
      #vhost:
    # PAS S3 config
    sharedStorage: {}
      #secretName:
      # Name of secret key for Access Key Id
      #accessKeyIdSecretKey: PAS_S3_ACCESS_KEY
      # Name of secret key for Secret Access Key
      #secretAccessKeySecretKey: PAS_S3_SECRET_ACCESS_KEY
      # S3 Bucket name for PAS
      #bucketName: "pas"
      # S3 URL for API Endpoint
      #s3Url:
      # S3 bucket subpath
      #s3BucketPath:
      # AWS region (if applicable)
      #region: "ca-central-1"
      # Maximum number of retries for initialization
      #initMaxRetryAttempts: 5
      # Number of seconds in between retries for initializaiton
      #initRetrySleepDuration: 5
      # Boolean representing whether to use SSL or not
      #useSsl: "true"
      # Boolean representing whether to verify SSL certs or not
      #verifyCerts: "true"
    # PAS Datastore settings
    datastore:
      # Service name if deployed in cluster
      #serviceName: redis-master
      # Hostname for external instance
      #host:
      #port: 6379
      #useSsl: "false"

  broker: {}
    #adminClientUser: sde
    #adminVhost: sde

  # S3 config from SDE
  sharedStorage: {}
    #secretName:
    # Name of secret key for Access Key Id
    #accessKeyIdSecretKey: PAS_S3_ACCESS_KEY
    # Name of secret key for Secret Access Key
    #secretAccessKeySecretKey: PAS_S3_SECRET_ACCESS_KEY
    # S3 Bucket name for PAS
    #bucketName: "pas"
    # S3 URL for API Endpoint
    #s3Url: "https://my-bucket.s3.us-west-2.amazonaws.com/"
    # S3 bucket subpath
    #s3BucketPath: "/path/to/storage/in/bucket/
    #s3AccessKey: "accesskey"
    #s3SecretKey: "secretKey"

  ## Configuration for Sentry
  # sentry:
  #   enabled: false
  #   environment: develop
  #   sampleRate: 0.1
  #   traceSampleRate: 0.1

#  enableNodeSelector: true

## Chart Configuration
# Include broker subchart in deployment
useBrokerSubchart: true
# Include shared storage subchart in deployment
minio:
    enabled: false
# Include datastore subchart in deployment
datastore:
    enabled: false

### PAS Plugin Service container configuration
#imageName: pas-plugin-service
##  Default image tag.
#imageTag: <App Version>

## Name of the celery queue to listen on
#queueName: plugin_service_worker
## Celery result backend
resultBackend: rpc://
## Celery log level. One of DEBUG, INFO, WARNING, ERROR, CRITICAL
#celeryLogLevel: INFO
## Number of celery worker processes to launch
#celeryWorkerCount: 4
## Max number of celery tasks before recreating the worker.
## Lowering the amount can help keep memory usage lower over time.
#celeryMaxTasksPerChild: 10
## Number of seconds for a sync task to perform
#syncTaskTimeoutSeconds: "1800"

## Username for broker user
#brokerUser: pas
## Name of secret containing the broker password
#brokerSecretName: broker-secrets
## Secret key containing the broker password
#brokerPasswordSecretKey: ADMIN_BROKER_PASSWORD

# PAS broker config
broker: {}
  #secretName:
  #passwordSecretKey:

# PAS Plugin Worker service S3 config
sharedStorage: {}
  # Name of secret key for Access Key Id
  #accessKeyIdSecretKey: PAS_S3_ACCESS_KEY
  # Name of secret key for Secret Access Key
  #secretAccessKeySecretKey: PAS_S3_SECRET_ACCESS_KEY
  # S3 Bucket name for PAS
  #bucketName:
  # S3 bucket subpath
  #s3BucketPath:
  # AWS region (if applicable)
  #region:
  # Maximum number of retries for initialization
  #initMaxRetryAttempts: 5
  # Number of seconds in between retries for initializaiton
  #initRetrySleepDuration: 5
  # Boolean representing whether to use SSL or not
  #useSsl:
  # Boolean representing whether to verify SSL certs or not
  #verifyCerts:

## User/Group options
# uid: 999
# gid: 101
# fsgid: 101

## Configuration for Sentry
# sentry:
#   enabled: false
#   dsn: https://xxxxxx.ingest.sentry.io/000000
#   environment: develop
#   sampleRate: 0.1
#   traceSampleRate: 0.1
