# Identifies if our package should be deployed or ignored
sdelements:
  enabled: true
  # The Git location of the package Helm chart
  git:
    repo: https://repo1.dso.mil/big-bang/product/community/sdelements
    branch: main
    path: chart
  flux:
    timeout: 30m
    # This should really work but for whatever reason kyverno will also depends on it and puts helm release into an infinite dependency loop
    #dependsOn:
    #  - name: minio-operator
  values:
    global:
      storageClass: local-path
      registrySecretName: private-registry
      sharedStorage:
        bucketName: sde-bucket        # If using MinIO, ensure value matches a bucket in `minio` section
        s3Url: http://sdelements-minio-hl:9000/
        s3AccessKey: accesskey        # If using MinIO, ensure value matches `accessKey` in `minio` section
        s3SecretKey: secretkey
      # bitnami charts set this differently
      imagePullSecrets:
        - private-registry
    sc-datastore:
      clientPassword: default
      imageTag: 6.2.14-ubi9
    sc-mail:
      imageTag: 1.4-9.4-001
    worker:
      imageTag: 2024.1.42-9.4-001
    reporting:
      imageTag: 2024.1.42-9.4-001
    postgresql:
      image:
        tag: 12.19
      auth:
        password: default
        postgressPassword: default
      primary:
        containerSecurityContext:
          runAsUser: 26
          runAsGroup: 26
        podSecurityContext:
          fsGroup: 26
        podLabels:
          sidecar.istio.io/inject: "false"
    rabbitmq:
      image:
        tag: 3.12.14
      auth:
        password: default
        erlangCookie: default
      containerSecurityContext:
        runAsUser: 1001
      podSecurityConext:
        fsGroup: 1001
      initContainers: []
      extraEnvVars: []
      podLabels:
          sidecar.istio.io/inject: "false"
      readinessProbe:
        enabled: false
      ulimitNofiles: ""
    web:
      imageTag: 2024.1.42-9.4-001
    sc-jitt:
      imageTag: 2024.1.1-9.4-001
    sc-cam:
      brokerPassword: default
      databasePassword: default
      enabled: true
      imageTag: 2024.1.5-9.4-001
      initImageTag: 2024.1.2-8.10-001
    minio:
      image:
        repository: registry1.dso.mil/ironbank/opensource/minio/minio
        tag: RELEASE.2022-11-08T05-27-07Z
      mcImage:
        repository: registry1.dso.mil/ironbank/opensource/minio/mc
        tag: RELEASE.2022-11-07T23-47-39Z
      configPathmc: "/tmp/minio/mc/"
      extraEnvVars:
        - name: MINIO_CLIENT_CONFIG_DIR
          value: "/.mc"
      enabled: false
      rootUser: admin
      rootPassword: password
      tls:
        enabled: false
      buckets:
        - name: sde-bucket            # should match global.sharedStorage.bucketName
          policy: none
          purge: false
      users:
        - accessKey: accesskey    # should match global.sharedStorage.s3AccessKey
          secretKey: secretkey    # should match global.sharedStorage.s3SecretKey
          policy: readwrite
    minio-tenant:
      enabled: true
      tenant:
        name: sdelements-minio
        image:
          tag: RELEASE.2024-06-04T19-20-08Z
        imagePullSecret:
          name: private-registry
        env:
          - name: MINIO_BROWSER
            value: "off"
        pools:
          - servers: 1
            name: pool-0
            volumesPerServer: 4
            size: 10Gi
        certificate:
          requestAutoCert: false
        buckets:
          - name: sde-bucket
        configuration:
          name: sdelements-minio-env-configuration
      secrets:
        name: sdelements-minio-env-configuration
        accessKey: accesskey
        secretKey: secretkey
    job:
      specifications:
        trend-reporting:
          imageTag: 2024.1.4-8.10-001
          schedule: "0 0 30 2 0"
        alm-hourly:
          schedule: "0 0 30 2 0"
        alm-daily:
          schedule: "0 0 30 2 0"
        alm-weekly:
          schedule: "0 0 30 2 0"
        alm-monthly:
          schedule: "0 0 30 2 0"
        database-backup:
          schedule: "0 0 30 2 0"
        clear-expired-sessions:
          schedule: "0 0 30 2 0"
        refresh-task-relevance:
          schedule: "0 0 30 2 0"
        send-new-relevant-task-notifications:
          schedule: "0 0 30 2 0"
        time-since:
          schedule: "0 0 30 2 0"
        metrics:
          schedule: "0 0 30 2 0"
        cancel-external-sync-jobs:
          schedule: "0 0 30 2 0"
    sde:
      fqdn: sdelements.dev.bigbang.mil
      jwtSecret: default
      secretKey: default
      superuserPassword: default
      enableJITT: false
      systemAdminEmail: default@example.com
    istio:
      enabled: true
      gateways:
        - istio-system/public
      host: sdelements.dev.bigbang.mil
    bbtests:
      enabled: false
# Uncomment the following lines to deploy imagePullSecret
#registryCredentials:
#  registry: registry1.dso.mil
#  username: <username>
#  password: <password>
#  email: ""

kyverno:
  enabled: false
kyvernoPolicies:
  enabled: false
kyvernoReporter:
  enabled: false

# Network Policies
networkPolicies:
  enabled: false

# Istio
istioOperator:
  enabled: true
istio:
  enabled: true

# Gatekeeper
gatekeeper:
  enabled: false
clusterAuditor:
  enabled: false

# Logging
eckOperator:

# Network Policies
networkPolicies:
  enabled: false

# Gatekeeper
gatekeeper:
  enabled: false
clusterAuditor:
  enabled: false

# Logging
eckOperator:
  enabled: false
elasticsearchKibana:
  enabled: false
fluentbit:
  enabled: false
promtail:
  enabled: false
loki:
  enabled: false

# Monitoring
monitoring:
  enabled: false
grafana:
  enabled: false

# Other Tools
jaeger:
  enabled: false
kiali:
  enabled: false
twistlock:
  enabled: false
tempo:
  enabled: false
neuvector:
  enabled: false

addons:
  minioOperator:
    enabled: true
