# Identifies if our package should be deployed or ignored
sdelements:
  enabled: true
  # The Git location of the package Helm chart
  git:
    repo: https://repo1.dso.mil/big-bang/apps/sandbox/sdelements
    branch: main
    path: chart
  flux: {}
  values: 
    global:
      storageClass: local-path
      registrySecretName: private-registry
    datastore:
      initImageTag: 1.1
      imageTag: 6.2.10
    reporting:
      imageTag: 2022.4.33
    worker:
      imageTag: 2022.4.33
    sc-mail:
      imageTag: 1.1
    sc-database:
      imageTag: 12.13
    sc-broker:
      imageTag: v3.8.35
    sc-jitt:
      imageTag: 2022.4.33
    web:
      imageTag: 12.6
    sde:
      enableJITT: false
    
# Network Policies
networkPolicies:
  enabled: false

# Istio
istiooperator:
  enabled: false
istio:
  enabled: false

# Gatekeeper
gatekeeper:
  enabled: false
clusterAuditor:
  enabled: false

# Logging
eckoperator:
  enabled: false
logging:
  enabled: false
fluentbit:
  enabled: false

# Monitoring
monitoring:
  enabled: false

# Other Tools
jaeger:
  enabled: false
kiali:
  enabled: false
twistlock:
  enabled: false

addons:
  minioOperator:
    enabled: false
  minio:
    enabled: false
