# Identifies if our package should be deployed or ignored
sdelements:
  enabled: true
  # The Git location of the package Helm chart
  git:
    repo: https://repo1.dso.mil/big-bang/product/community/sdelements
    branch: main
    path: chart
  flux:
    timeout: 30m
    # This should really work but for whatever reason kyverno will also depends on it and puts helm release into an infinite dependency loop
    #dependsOn:
    #  - name: minio-operator
  values:
    global:
      storageClass: local-path
      registrySecretName: private-registry
      sharedStorage:
        bucketName: sde-bucket        # If using MinIO, ensure value matches a bucket in `minio` section
        s3Url: http://sdelements-minio-hl:9000/
        s3AccessKey: accesskey        # If using MinIO, ensure value matches `accessKey` in `minio` section
        s3SecretKey: secretkey
      # bitnami charts set this differently
      imagePullSecrets:
        - private-registry
    sde:
      fqdn: sdelements.dev.bigbang.mil
      jwtSecret: default
      secretKey: default
      superuserPassword: default
      enableJITT: false
      systemAdminEmail: default@example.com
    sc-datastore:
      clientPassword: default
    postgresql:
      auth:
        password: default
        postgressPassword: default
    rabbitmq:
      auth:
        password: default
        erlangCookie: default
    minio:
      enabled: false
      rootUser: admin
      rootPassword: password
      tls:
        enabled: false
      buckets:
        - name: sde-bucket            # should match global.sharedStorage.bucketName
          policy: none
          purge: false
      users:
        - accessKey: accesskey    # should match global.sharedStorage.s3AccessKey
          secretKey: secretkey    # should match global.sharedStorage.s3SecretKey
          policy: readwrite
    minio-tenant:
      enabled: true
      tenant:
        imagePullSecret:
          name: private-registry
        env:
          - name: MINIO_BROWSER
            value: "off"
        pools:
          - servers: 1
            name: pool-0
            volumesPerServer: 4
            size: 10Gi
      secrets:
        accessKey: accesskey
        secretKey: secretkey
    istio:
      enabled: true
      gateways:
        - istio-system/public
      host: sdelements.dev.bigbang.mil
    bbtests:
      enabled: false
# Uncomment the following lines to deploy imagePullSecret
#registryCredentials:
#  registry: registry1.dso.mil
#  username: <username>
#  password: <password>
#  email: ""

kyverno:
  enabled: false
kyvernoPolicies:
  enabled: false
kyvernoReporter:
  enabled: false

# Network Policies
networkPolicies:
  enabled: false

# Gatekeeper
gatekeeper:
  enabled: false

# Logging
eckOperator:

# Network Policies
networkPolicies:
  enabled: false

# Gatekeeper
gatekeeper:
  enabled: false
clusterAuditor:
  enabled: false

# Logging
eckOperator:
  enabled: false
elasticsearchKibana:
  enabled: false
fluentbit:
  enabled: false
promtail:
  enabled: false
loki:
  enabled: false

# Monitoring
monitoring:
  enabled: false
grafana:
  enabled: false

# Other Tools
kiali:
  enabled: false
twistlock:
  enabled: false
tempo:
  enabled: false
neuvector:
  enabled: false

addons:
  minioOperator:
    enabled: true
