# Identifies if our package should be deployed or ignored
sdelements:
  enabled: true
  # The Git location of the package Helm chart
  git:
    repo: https://repo1.dso.mil/big-bang/apps/sandbox/sdelements
    branch: main
    path: chart
  flux: {}
  values:
    global:
      storageClass: local-path
      registrySecretName: private-registry
      # bitnami charts set this differently
      imagePullSecrets:
        - private-registry
    sc-datastore:
      clientPassword: default
      imageTag: 6.2.14-ubi9
    sc-mail:
      imageTag: 1.2-8.9
    worker:
      imageTag: 2023.3.36-8.9
    reporting:
      imageTag: 2023.3.36-8.9
    postgresql:
      image:
        tag: 12.17
      auth:
        password: default
        postgressPassword: default
    rabbitmq:
      image:
        tag: 3.12.11
      auth:
        password: default
        erlangCookie: default
    web:
      imageTag: 2023.3.36-8.9
    sc-jitt:
      imageTag: 2023.3.0-8.9
    sc-cam:
      brokerPassword: default
      databasePassword: default
      enabled: true
      imageTag: 2023.3.6-8.9
      initImageTag: 2023.3.4-8.9
    minio:
      image:
        tag: RELEASE.2023-12-20T01-00-02Z
      mcImage:
        tag: RELEASE.2023-12-14T00-37-41Z
    job:
      specification:
        trend-reporting:
          imageTag: 2023.3.3-8.9
    sde:
      fqdn: sdelements.bigbang.dev
      jwtSecret: default
      secretKey: default
      superuserPassword: default
      enableJITT: false
      systemAdminEmail: default@example.com
    istio:
      host: sdelements.bigbang.dev
# Uncomment the following lines to deploy imagePullSecret
#registryCredentials:
#  registry: registry1.dso.mil
#  username: <username>
#  password: <password>
#  email: ""

# Network Policies
networkPolicies:
  enabled: false

# Istio
istioOperator:
  enabled: false
istio:
  enabled: false

# Gatekeeper
gatekeeper:
  enabled: false
clusterAuditor:
  enabled: false

# Logging
eckOperator:
  enabled: false
elasticsearchKibana:
  enabled: false
fluentbit:
  enabled: false
promtail:
  enabled: false
loki:
  enabled: false

# Monitoring
monitoring:
  enabled: false
grafana:
  enabled: false

# Other Tools
jaeger:
  enabled: false
kiali:
  enabled: false
twistlock:
  enabled: false
addons:
  minioOperator:
    enabled: false
  minio:
    enabled: false
