# Identifies if our package should be deployed or ignored
sdelements:
  enabled: true
  # The Git location of the package Helm chart
  git:
    repo: https://repo1.dso.mil/big-bang/product/community/sdelements
    branch: main
    path: chart
  flux: {}
  values:
    global:
      storageClass: local-path
      registrySecretName: private-registry
      sharedStorage:
        bucketName: sde-bucket        # If using MinIO, ensure value matches a bucket in `minio` section
        s3Url: http://sdelements-minio-hl:9000/
        s3AccessKey: accesskey        # If using MinIO, ensure value matches `accessKey` in `minio` section
        s3SecretKey: secretkey
      # bitnami charts set this differently
      imagePullSecrets:
        - private-registry
    sc-datastore:
      clientPassword: default
      imageTag: 6.2.14-ubi9
    sc-mail:
      imageTag: 1.3-8.9
    worker:
      imageTag: 2023.4.23-8.9
    reporting:
      imageTag: 2023.4.23-8.9
    postgresql:
      image:
        tag: 12.18
      auth:
        password: default
        postgressPassword: default
    rabbitmq:
      image:
        tag: 3.12.13
      auth:
        password: default
        erlangCookie: default
    web:
      imageTag: 2023.4.23-8.9
    sc-jitt:
      imageTag: 2023.3.2-8.9
    sc-cam:
      brokerPassword: default
      databasePassword: default
      enabled: true
      imageTag: 2023.4.8-8.9
      initImageTag: 2023.4.0-8.9
    minio-tenant:
      enabled: true
      tenant:
        name: sdelements-minio
        imagePullSecret:
          name: private-registry
        env:
          - name: MINIO_BROWSER
            value: "off"
        pools:
          - servers: 1
            name: pool-0
            volumesPerServer: 4
            size: 10Gi
        certificate:
          requestAutoCert: false
        buckets:
          - name: sde-bucket
        configuration:
          name: sdelements-minio-env-configuration
      secrets:
        name: sdelements-minio-env-configuration
        accessKey: accesskey
        secretKey: secretkey
    job:
      specifications:
        trend-reporting:
          imageTag: 2023.4.2-8.9
    sde:
      fqdn: sdelements.bigbang.dev
      jwtSecret: default
      secretKey: default
      superuserPassword: default
      enableJITT: false
      systemAdminEmail: default@example.com
    istio:
      host: sdelements.bigbang.dev
# Uncomment the following lines to deploy imagePullSecret
#registryCredentials:
#  registry: registry1.dso.mil
#  username: <username>
#  password: <password>
#  email: ""

# Network Policies
networkPolicies:
  enabled: false

# Istio
istioOperator:
  enabled: false
istio:
  enabled: false

# Gatekeeper
gatekeeper:
  enabled: false
clusterAuditor:
  enabled: false

# Logging
eckOperator:
  enabled: false
elasticsearchKibana:
  enabled: false
fluentbit:
  enabled: false
promtail:
  enabled: false
loki:
  enabled: false

# Monitoring
monitoring:
  enabled: false
grafana:
  enabled: false

# Other Tools
jaeger:
  enabled: false
kiali:
  enabled: false
twistlock:
  enabled: false
addons:
  minioOperator:
    enabled: false
  minio:
    enabled: false
