# Identifies if our package should be deployed or ignored
sdelements:
  enabled: true
  # The Git location of the package Helm chart
  git:
    repo: https://repo1.dso.mil/big-bang/apps/sandbox/sdelements
    branch: main
    path: chart
  flux: {}
  values:
    global:
      storageClass: local-path
      registrySecretName: private-registry
    sc-datastore:
      clientPassword: default
      initImageTag: 1.1
      imageTag: 6.2.12
    sc-mail:
      imageTag: "1.1"
    sc-database:
      imageTag: "12.13"
      clientPassword: default
    sc-broker:
      imageTag: "v3.8.35"
      clientPassword: default
    web:
      imageTag: "12.6"
    sde:
      fqdn: sdelements.bigbang.dev
      jwtSecret: default
      secretKey: default
      superuserPassword: default
      enableJITT: false
      systemAdminEmail: default@example.com
    istio:
      host: sdelements.bigbang.dev
# Uncomment the following lines to deploy imagePullSecret
# registryCredentials:
#   registry: registry1.dso.mil
#   username: <username>
#   password: <password>
#   email: ""

# Network Policies
networkPolicies:
  enabled: false

# Istio
istioOperator:
  enabled: true
istio:
  enabled: true

# Gatekeeper
gatekeeper:
  enabled: false
clusterAuditor:
  enabled: false

# Logging
eckOperator:
  enabled: false
elasticsearchKibana:
  enabled: false
fluentbit:
  enabled: false
promtail:
  enabled: false
loki:
  enabled: false

# Monitoring
monitoring:
  enabled: false

# Other Tools
jaeger:
  enabled: false
kiali:
  enabled: false
twistlock:
  enabled: false
addons:
  minioOperator:
    enabled: false
  minio:
    enabled: false