# Identifies if our package should be deployed or ignored
sdelements:
  enabled: true
  # The Git location of the package Helm chart
  git:
    repo: https://repo1.dso.mil/big-bang/apps/sandbox/sdelements
    branch: main
    path: chart
  flux: {}
  values:
    global:
      storageClass: local-path
      registrySecretName: private-registry
      # bitnami charts set this differently
      imagePullSecrets:
        - private-registry
    sc-datastore:
      clientPassword: default
      initImageTag: 1.1
      imageTag: 6.2.12
    sc-mail:
      imageTag: "1.1-8.8"
    postgresql:
      image:
        tag: 12.15
      auth:
        password: default
        postgressPassword: default
    rabbitmq:
      image:
        tag: 3.12.6
      auth:
        password: default
        erlangCookie: default
    web:
      imageTag: "2023.2.49-1.25.2"
    job:
      specification:
        trend-reporting:
          imageTag: "0.0.3-8.8"
    sde:
      fqdn: sdelements.bigbang.dev
      jwtSecret: default
      secretKey: default
      superuserPassword: default
      enableJITT: false
      systemAdminEmail: default@example.com
    istio:
      host: sdelements.bigbang.dev
# Uncomment the following lines to deploy imagePullSecret
# registryCredentials:
#   registry: registry1.dso.mil
#   username: <username>
#   password: <password>
#   email: ""

# Network Policies
networkPolicies:
  enabled: false

# Istio
istioOperator:
  enabled: false
istio:
  enabled: false

# Gatekeeper
gatekeeper:
  enabled: false
clusterAuditor:
  enabled: false

# Logging
eckOperator:
  enabled: false
elasticsearchKibana:
  enabled: false
fluentbit:
  enabled: false
promtail:
  enabled: false
loki:
  enabled: false

# Monitoring
monitoring:
  enabled: false
grafana:
  enabled: false

# Other Tools
jaeger:
  enabled: false
kiali:
  enabled: false
twistlock:
  enabled: false
addons:
  minioOperator:
    enabled: false
  minio:
    enabled: false
