{{- $pkg := "sdelements" }}
{{- if (get .Values $pkg).enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $pkg }}
  labels:
    {{- if (get .Values $pkg).istio.enabled }}
    istio-injection: "disabled"
    {{- end }}
    app.kubernetes.io/name: {{ $pkg }}
    {{- include "commonLabels" . | nindent 4}}
{{- end }}
