### Default values for the Example (example) Helm Chart.
### This is a YAML-formatted file.
### Declare variables to be passed into your templates.

## Example specific options
global:
  enabled: true
  ## Configuration options and crentials to fetch images from private
  ## registries/repositories. These are provided by SDElements support staff on
  ## request upon purchase of the SDElements product.
  ##
  imageRegistry: sdelements.jfrog.io

  # Format: $imageRegistry $imageOrganization $imageSource $imageName $imageTag
  imageRegistryFormat: "%s/sde-docker-%s/%s/%s:%s"
  imageRegistryUsername: acmecorp
  imageRegistryPassword: SuperSecretPassword
  imageOrganization: prod #dev/staging/prod
  imagePullPolicy: IfNotPresent
  imageSource: sde/pas
  # imageTag: 1.0.3

  # Run containers as the root user rather than default unprivileged user
  # runAsRoot: true

  pas: {}
    # Environment variables for PAS image
    #maxPluginFileSize: '10000000'

  ## Configuration for Sentry
  # sentry:
  #   enabled: false
  #   environment: develop
  #   sampleRate: 0.1
  #   traceSampleRate: 0.1

#imageName: pas-static
#port: 80
# Service name of the PAS API service
#backendServiceName: pas-api-service
# Full URL to PAS API service
#pasBackendUrl: http://pas-api-service:8000
# TTL for DNS resolutions
#resolverTTL: 10
# URL path for readiness check
#readinessPath: /pas/api/redoc
# User/Group values for security context
#uid: 101
#gid: 101
#fsgid 33

## Configuration for Sentry
# sentry:
#   enabled: false
#   dsn: https://xxxxxx.ingest.sentry.io/000000
#   environment: develop
#   sampleRate: 0.1
#   traceSampleRate: 0.1

networkPolicies:
  pas-frontend:
    podSelector:
      matchLabels:
        name: "{{ include \"library.trimmedName\" . }}-pas-frontend"
    ingress:
      - selectors:
          - podSelector:
              matchLabels:
                name: "{{ include \"library.trimmedName\" . }}-web"
        ports:
          - port: '{{ index .Values "port" | int | default 8081 }}'
