apiVersion: v2
appVersion: 2.0.5
dependencies:
- name: sc-library
  repository: https://repository.securitycompass.com/artifactory/sde-helm-dev
  version: 1.1.4
- condition: useDatabaseSubchart
  name: sc-database
  repository: https://repository.securitycompass.com/artifactory/sde-helm-dev
  version: 1.3.6
- condition: useBrokerSubchart
  name: rabbitmq
  repository: https://charts.bitnami.com/bitnami
  version: 11.14.4
- condition: minio.enabled
  name: minio
  repository: https://charts.min.io/
  version: 5.0.14
- condition: useDatastoreSubchart
  name: sc-datastore
  repository: https://repository.securitycompass.com/artifactory/sde-helm-dev
  version: 1.0.3
description: SD Elements PAS API Service
home: https://docker.sdelements.com
icon: https://avatars0.githubusercontent.com/u/739346
keywords:
- sde
- sdelements
- pas
- backend
- python
- wsgi
maintainers:
- email: sdesupport@securitycompass.com
  name: Security Compass Technologies Ltd.
  url: https://www.securitycompass.com/
name: pas-api
sources:
- https://agra.sdelements.com/sd-elements/management_command_system
type: application
version: 2.0.5
