### Default values for the SDE Worker Helm Chart.
### This is a YAML-formatted file.
### Declare variables to be passed into your templates.

## Options & settings accessible by all charts
global:
  ## Provide a name in place of `sde` for `app:` labels
  ##
  #nameOverride: ""

  ## Provide a name to substitute for the full names of resources
  ##
  #fullnameOverride: ""

  ## Configuration options and crentials to fetch images from private
  ## registries/repositories. These are provided by SDElements support staff on
  ## request upon purchase of the SDElements product.
  ##
  imageRegistry: repository.securitycompass.com

  # Format: $imageRegistry $imageOrganization $imageSource $imageName $imageTag
  # repository.securitycompass.com/sde-docker-prod/sde/pas_api:latest
  imageRegistryFormat: "%s/sde-docker-%s/%s/%s:%s"
  imageRegistryUsername: acmecorp
  imageRegistryPassword: SuperSecretPassword
  imageOrganization: prod #dev/stagion/prod
  imageSource: sde
  imagePullPolicy: IfNotPresent
  #
  # Fully Qualified Domain Name(s)
  #
  # fqdn: example.com
  # DNS Aliases & Extra names
  # FQDN and alternateDnsNames are used to create DNS records and
  # get certificates issued dynamically.
  # Connections to URLs defined in these are encrypted by default using Cert Manager
  # and if not defined will fall back to Custom Certs/self-signed Certs.
  # alternateDnsNames:
  #  - alias.example.com
  #  - othername.example.com
  # alternateVirtualHosts are used to create config sections in the ingress and
  # can be optionally used with a custom cert.
  # When custom certs are configured any connections to these URLs will be encrypted using said certs,
  # in case custom certs are not configured the ingress will back to using self signed certs.
  # alternateVirtualHosts:
  #  - externally-managed-dns-record.example.com

  ## Feature flags that enable/disable subcharts and subchart features
  # that need to be specified before runtime because they affect how subcharts
  # deploy themselves
  #

  useSubcharts: false

  # Global PAS configuration
  pas:
    #databasePrefix: pas
    #databaseUser: pas
    #baseUrl: /pas
    # Enable or disable custom plugin functionality
    #enableCustomPlugins: true
    # Max file size for uploaded plugins (bytes)
    #maxPluginFileSize: 10000000
    # Name of the plugin service celery queue to listen on
    #pluginServiceQueueName: plugin_service_worker
    # Name of the async worker celery queue to listen on
    #asyncWorkerQueueName: pas_async_worker
    # Global secret name for PAS secrets
    #secretName:
    # Global PAS broker config
    broker: {}
      #user: pas
      #password:
      #secretName:
      #passwordSecretKey:
      #vhost:
    # Global PAS database config
    database: {}
      #user: pas
      #password:
      #secretName:
      #passwordSecretKey:
    # PAS S3 config
    sharedStorage: {}
      #secretName:
      # Name of secret key for Access Key Id
      #accessKeyIdSecretKey: PAS_S3_ACCESS_KEY
      # Name of secret key for Secret Access Key
      #secretAccessKeySecretKey: PAS_S3_SECRET_ACCESS_KEY
      # S3 Bucket name for PAS
      #bucketName: "pas"
      # S3 URL for API Endpoint
      #s3Url:
      # S3 bucket subpath
      #s3BucketPath:
      # AWS region (if applicable)
      #region: "ca-central-1"
      # Maximum number of retries for initialization
      #initMaxRetryAttempts: 5
      # Number of seconds in between retries for initializaiton
      #initRetrySleepDuration: 5
      # Boolean representing whether to use SSL or not
      #useSsl: "true"
      # Boolean representing whether to verify SSL certs or not
      #verifyCerts: "true"
    # PAS Datastore settings
    datastore: { }
      # Datastore service name
      #serviceName: datastore-service
      # Datastore port
      #port: 6379
      #useSsl: false
      # Datastore client username
      #clientUsername:
      # Datastore client password
      #clientPassword:

  database: {}
    #adminClientUser: sde
    #host:
    #port:

  broker:
    #adminClientUser: rabbit 
    adminVhost: rabbit
    #user: rabbit
    #requireSSL: false
    #host: broker-headless
    #port: 5672
    #url: amqp://www.example.com

  # S3 config from SDE
  sharedStorage: {}
    #secretName:
    # Name of secret key for Access Key Id
    #accessKeyIdSecretKey: PAS_S3_ACCESS_KEY
    # Name of secret key for Secret Access Key
    #secretAccessKeySecretKey: PAS_S3_SECRET_ACCESS_KEY
    # S3 Bucket name for PAS
    #bucketName: "pas"
    # S3 URL for API Endpoint
    #s3Url: "https://my-bucket.s3.us-west-2.amazonaws.com/"
    # S3 bucket subpath
    #s3BucketPath: "/path/to/storage/in/bucket/
    #s3AccessKey: "accesskey"
    #s3SecretKey: "secretKey"

  # Global datastore config
  datastore: {}
    # Datastore service name
    #serviceName: datastore-service
    # Datastore port
    #port: 6379
    #useSsl: false
    # Datastore client username
    #clientUsername:
    # Datastore client password
    #clientPassword:

  ## Configuration for Sentry
  # sentry:
  #   enabled: false
  #   environment: develop
  #   sampleRate: 0.1
  #   traceSampleRate: 0.1

  ## Configuration for running on Openshift
  # openshift:
  #   enabled: false

sc-database: {}
  #secretName:

# PAS broker config
broker: {}
  #secretName:
  #passwordSecretKey:

rabbitmq:
  nameOverride: "broker"
  #replicaCount: 1
  image:
    # registry: repository.securitycompass.com
    repository: sde-docker-prod/sde/rabbitmq
    # tag: 3.11.15-debian-11-r0
    #pullSecrets:
    #- pas-api-registry-secret
  auth:
    username: rabbit
    #password: "myrabbitmqpassword"
    #existingPasswordSecret: ""
  extraConfiguration: |-
    default_vhost = {{ .Values.global.broker.adminVhost }}

  ## URL is mutually exclusive to user/pass/host/vhost and takes precidence over
  ## those values if specified
  #url: amqp://user:pass@host:post/vhost
  resources:
    requests:
      cpu: 10m
      memory: 150Mi
    limits:
      cpu: 2
      memory: 2048Mi
  # metrics:
  #   enabled: false
  #   serviceMonitor:
  #     enabled: false

minio:
  enabled: false
  mode: standalone
  persistence:
    size: 8Gi
  resources:
    requests:
      memory: 256Mi
  # The bucket name should match what you've defined in global.sharedStorage.bucketName
  buckets:
    - name: plugin
      policy: none
      purge: false
  serviceAccount:
    create: true
    name: "minio-sa"

## Chart Configuration
# Include database subchart in deployment
useDatabaseSubchart: true
# Include broker subchart in deployment
useBrokerSubchart: true
# Include the datastore subchart in deployment
useDatastoreSubchart: true
# Include SDE secret definition
includeSDESecret: true

useLocalDevDbConfig: true

## PAS API container configuration
#imageName: pas-api
#imageTag: <App Version>

# SDE API Url
sdeAPIServiceMethod: http
#sdeAPIServiceName: mock-sde
#sdeAPIServicePort: 8000

# URL for a supported result backend to override the default backend
#resultBackend:

# Name of queue to enqueue SDE jobs
#sdeQueueName: celery
# Python console logging level. One of DEBUG, INFO, WARNING, ERROR, CRITICAL
#logLevel: INFO
# The number of gunicorn workers to spin up
#workerCount: 4
# Gunicorn log level
#gunicornLogLevel: info

## PAS init container configuration
#initImageName: pas-app-init
#initImageTag: <App Version>

## User/Group options
# uid: 999
# gid: 999
# fsgid: 999

# PAS Init container config
admin:
  database: {}
    # The name of the default database
    #defaultDatabase: postgres
    # Admin username
    #user: postgres
    #secretName:
    #passwordSecretKey:
  broker: {}
    # Admin username
    #user: rabbit
    #secretName:
    #passwordSecretKey:

# PAS database config
database: {}
  #secretName:
  #passwordSecretKey:

sde:
  # SDE JWT Secret
  #jwtSecret: s3cr3tk3y
  # Secret name for SDE secrets
  #secretName:
  # SDE broker secret config
  broker: {}
    #secretName:
    #passwordSecretKey:

# PAS API service S3 config
sharedStorage: {}
  # Name of secret key for Access Key Id
  #accessKeyIdSecretKey: PAS_S3_ACCESS_KEY
  # Name of secret key for Secret Access Key
  #secretAccessKeySecretKey: PAS_S3_SECRET_ACCESS_KEY
  # S3 Bucket name for PAS
  #bucketName:
  # S3 bucket subpath
  #s3BucketPath:
  # AWS region (if applicable)
  #region:
  # Maximum number of retries for initialization
  #initMaxRetryAttempts: 5
  # Number of seconds in between retries for initializaiton
  #initRetrySleepDuration: 5
  # Boolean representing whether to use SSL or not
  #useSsl:
  # Boolean representing whether to verify SSL certs or not
  #verifyCerts:

## Configuration for Sentry
# sentry:
#   enabled: false
#   dsn: https://xxxxxx.ingest.sentry.io/000000
#   environment: develop
#   sampleRate: 0.1
#   traceSampleRate: 0.1

networkPolicies:
  pas-api:
    podSelector:
      matchLabels:
        name: "{{ include \"library.trimmedName\" . }}-pas-api"
    ingress:
      - selectors:
          - podSelector:
              matchLabels:
                name: "{{ include \"library.trimmedName\" . }}-pas-frontend"
          - podSelector:
              matchLabels:
                name: "{{ include \"library.trimmedName\" . }}-worker-10"
          - podSelector:
              matchLabels:
                name: "{{ include \"library.trimmedName\" . }}-worker-17"
          - podSelector:
              matchLabels:
                name: "{{ include \"library.trimmedName\" . }}-worker-15-sde-medium"
          - podSelector:
              matchLabels:
                name: "{{ include \"library.trimmedName\" . }}-worker-18-sde-low"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-alm-hourly"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-alm-daily"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-alm-weekly"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-alm-monthly"
        ports:
          - port: '{{ index .Values "port" | default 8000 }}'
