{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-egress-default-deny
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-egress-dns
spec:
  podSelector: {} # all pods in Release namespace
  policyTypes:
    - Egress
  egress:
    {{- if .Values.networkPolicies.egressDns }}
      {{- toYaml .Values.networkPolicies.egressDns | nindent 4 }}
    {{- end}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-egress
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    {{- if .Values.networkPolicies.egress }}
      {{- toYaml .Values.networkPolicies.egress | nindent 4 }}
    {{- end}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-default-deny
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-in-namespace
spec:
  podSelector: {} # all pods
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector: {} # all pods in namespace
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-istio-web
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
    {{- toYaml .Values.networkPolicies.ingress | nindent 4 }}
{{- end }}