{{- if .Values.efsVolumes.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sde-loader-efs-pv
  namespace: {{ .Release.Namespace }}
spec:
  volumeMode: Filesystem
  capacity:
    storage: {{ .Values.efsVolumes.loaderSize }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  claimRef:
    namespace: sdelements
    name: sdelements-loader-volume-claim
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.efsVolumes.loader }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sde-haystack-efs-pv
  namespace: {{ .Release.Namespace }}
spec:
  volumeMode: Filesystem
  capacity:
    storage: {{ .Values.efsVolumes.haystackSize }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  claimRef:
    namespace: sdelements
    name: sdelements-haystack-volume-claim
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.efsVolumes.haystack }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sde-media-efs-pv
  namespace: {{ .Release.Namespace }}
spec:
  volumeMode: Filesystem
  capacity:
    storage: {{ .Values.efsVolumes.mediaSize }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  claimRef:
    namespace: sdelements
    name: sdelements-media-volume-claim
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.efsVolumes.media }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sde-static-efs-pv
  namespace: {{ .Release.Namespace }}
spec:
  volumeMode: Filesystem
  capacity:
    storage: {{ .Values.efsVolumes.staticSize }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  claimRef:
    namespace: sdelements
    name: sdelements-static-volume-claim
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.efsVolumes.static }}
{{- end }}
