### Default values for the SDE Worker Helm Chart.
### This is a YAML-formatted file.
### Declare variables to be passed into your templates.

## Options & settings accessible by all charts
global:
  ## Default image tag.
  ## The version of container images for SDE to run
  ## Ref: https://docs.sdelements.com
  ##
  # imageTag: latest

  ## Provide a name in place of `sde` for `app:` labels
  ##
  #nameOverride: ""

  ## Provide a name to substitute for the full names of resources
  ##
  #fullnameOverride: ""

  ## Configuration options and crentials to fetch images from private
  ## registries/repositories. These are provided by SDElements support staff on
  ## request upon purchase of the SDElements product.
  ##
  imageRegistry: repository.securitycompass.com

  # Format: $imageRegistry $imageOrganization $imageSource $imageName $imageTag
  # repository.securitycompass.com/sde-docker-prod/sde/pas/pas_api:latest
  imageRegistryFormat: "%s/sde-docker-%s/%s/%s:%s"
  imageRegistryUsername: acmecorp
  imageRegistryPassword: SuperSecretPassword
  imageOrganization: prod #dev/staging/prod
  imageSource: sde
  imagePullPolicy: IfNotPresent

  pas:
    enabled: false
    databasePrefix: pas
    database:
      user: pas
      #password:
      # Secret name to use for all PAS services
      #secretName: pas-secrets
      # Secret key to use for all PAS services
      passwordSecretKey: PAS_DATABASE_PASSWORD
    broker:
      user: pas
      #password:
      # Vhost to use for all PAS services
      #vhost: rabbit
      # Secret name to use for all PAS services
      #secretName: pas-secrets
      # Secret key to use for all PAS services
      passwordSecretKey: PAS_BROKER_PASSWORD
    # PAS Datastore settings
    datastore: { }
      # Datastore service name
      #serviceName: datastore-service
      # Datastore port
      #port: 6379
      #useSsl: false
      # Datastore client username
      #clientUsername:
      # Datastore client password
      #clientPassword:

    baseUrl: /pas
    # Enable or disable custom plugin functionality
    enableCustomPlugins: true
    # File size limit for plugin files
    #maxPluginFileSize: 10000000
    # Name of the plugin service celery queue to listen on
    #pluginServiceQueueName: plugin_service_worker
    # Name of the async worker celery queue to listen on
    #asyncWorkerQueueName: pas_async_worker
    # PAS S3 config
    sharedStorage: {}
      #secretName:
      # Name of secret key for Access Key Id
      #accessKeyIdSecretKey: PAS_S3_ACCESS_KEY
      # Name of secret key for Secret Access Key
      #secretAccessKeySecretKey: PAS_S3_SECRET_ACCESS_KEY
      # S3 Bucket name for PAS
      #bucketName: "pas"
      # S3 URL for API Endpoint
      #s3Url:
      # S3 bucket subpath
      #s3BucketPath:
      # AWS region (if applicable)
      #region: "ca-central-1"
      # Maximum number of retries for initialization
      #initMaxRetryAttempts: 5
      # Number of seconds in between retries for initializaiton
      #initRetrySleepDuration: 5
      # Boolean representing whether to use SSL or not
      #useSsl: true
      # Boolean representing whether to verify SSL certs or not
      #verifyCerts: true
  # S3 config from SDE
  sharedStorage: {}
    #secretName:
    # Name of secret key for Access Key Id
    #accessKeyIdSecretKey: PAS_S3_ACCESS_KEY
    # Name of secret key for Secret Access Key
    #secretAccessKeySecretKey: PAS_S3_SECRET_ACCESS_KEY
    # S3 Bucket name for PAS
    #bucketName: "pas"
    # S3 URL for API Endpoint
    #s3Url: "https://my-bucket.s3.us-west-2.amazonaws.com/"
    # S3 bucket subpath
    #s3BucketPath: "/path/to/storage/in/bucket/
    #s3AccessKey: "accesskey"
    #s3SecretKey: "secretKey"

  # Global datastore config
  datastore: {}
    # Datastore service name
    #serviceName: datastore-service
    # Datastore port
    #port: 6379
    #useSsl: false
    # Datastore client username
    #clientUsername:
    # Datastore client password
    #clientPassword:

  ## Configuration for Sentry
  # sentry:
  #   enabled: false
  #   environment: develop
  #   sampleRate: 0.1
  #   traceSampleRate: 0.1

  thirdPartyCACertificates:
    # Enable use of custom CA certificates. Externally defined certs are expected to have a `.crt` file extension
    enabled: false
    # The external config map and secret should contain all PEM-formated CA certificates
    #externalConfigMapName: "my-k8s-ca-certificate-configmap-name"
    #externalSecretName: "my-k8s-ca-certificate-secret-name"
    # This should only be set if minio.tlsCreateSelfSigned=true in the "sde" parent helm chart
    #minioSelfSignedCertSecret: "{{ include \"library.trimmedName\" . }}-minio-server-tls-secrets"
    # You may define a PEM-formatted certificate
    #certs:
    #  apricot.crt: |-
    #    -----BEGIN CERTIFICATE-----
    #    MIIFWzCCA0OgAwIBAgIQTfQrldHumzpMLrM7jRBd1jANBgkqhkiG9w0BAQsFADBm
    #    MQswCQYDVQQGEwJVUzEzMDEGA1UEChMqKFNUQUdJTkcpIEludGVybmV0IFNlY3Vy
    #    aXR5IFJlc2VhcmNoIEdyb3VwMSIwIAYDVQQDExkoU1RBR0lORykgUHJldGVuZCBQ
    #    ZWFyIFgxMB4XDTIwMDkwNDAwMDAwMFoXDTI1MDkxNTE2MDAwMFowWTELMAkGA1UE
    #    BhMCVVMxIDAeBgNVBAoTFyhTVEFHSU5HKSBMZXQncyBFbmNyeXB0MSgwJgYDVQQD
    #    Ex8oU1RBR0lORykgQXJ0aWZpY2lhbCBBcHJpY290IFIzMIIBIjANBgkqhkiG9w0B
    #    AQEFAAOCAQ8AMIIBCgKCAQEAu6TR8+74b46mOE1FUwBrvxzEYLck3iasmKrcQkb+
    #    gy/z9Jy7QNIAl0B9pVKp4YU76JwxF5DOZZhi7vK7SbCkK6FbHlyU5BiDYIxbbfvO
    #    L/jVGqdsSjNaJQTg3C3XrJja/HA4WCFEMVoT2wDZm8ABC1N+IQe7Q6FEqc8NwmTS
    #    nmmRQm4TQvr06DP+zgFK/MNubxWWDSbSKKTH5im5j2fZfg+j/tM1bGaczFWw8/lS
    #    nukyn5J2L+NJYnclzkXoh9nMFnyPmVbfyDPOc4Y25aTzVoeBKXa/cZ5MM+WddjdL
    #    biWvm19f1sYn1aRaAIrkppv7kkn83vcth8XCG39qC2ZvaQIDAQABo4IBEDCCAQww
    #    DgYDVR0PAQH/BAQDAgGGMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAS
    #    BgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBTecnpI3zHDplDfn4Uj31c3S10u
    #    ZTAfBgNVHSMEGDAWgBS182Xy/rAKkh/7PH3zRKCsYyXDFDA2BggrBgEFBQcBAQQq
    #    MCgwJgYIKwYBBQUHMAKGGmh0dHA6Ly9zdGcteDEuaS5sZW5jci5vcmcvMCsGA1Ud
    #    HwQkMCIwIKAeoByGGmh0dHA6Ly9zdGcteDEuYy5sZW5jci5vcmcvMCIGA1UdIAQb
    #    MBkwCAYGZ4EMAQIBMA0GCysGAQQBgt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCN
    #    DLam9yN0EFxxn/3p+ruWO6n/9goCAM5PT6cC6fkjMs4uas6UGXJjr5j7PoTQf3C1
    #    vuxiIGRJC6qxV7yc6U0X+w0Mj85sHI5DnQVWN5+D1er7mp13JJA0xbAbHa3Rlczn
    #    y2Q82XKui8WHuWra0gb2KLpfboYj1Ghgkhr3gau83pC/WQ8HfkwcvSwhIYqTqxoZ
    #    Uq8HIf3M82qS9aKOZE0CEmSyR1zZqQxJUT7emOUapkUN9poJ9zGc+FgRZvdro0XB
    #    yphWXDaqMYph0DxW/10ig5j4xmmNDjCRmqIKsKoWA52wBTKKXK1na2ty/lW5dhtA
    #    xkz5rVZFd4sgS4J0O+zm6d5GRkWsNJ4knotGXl8vtS3X40KXeb3A5+/3p0qaD215
    #    Xq8oSNORfB2oI1kQuyEAJ5xvPTdfwRlyRG3lFYodrRg6poUBD/8fNTXMtzydpRgy
    #    zUQZh/18F6B/iW6cbiRN9r2Hkh05Om+q0/6w0DdZe+8YrNpfhSObr/1eVZbKGMIY
    #    qKmyZbBNu5ysENIK5MPc14mUeKmFjpN840VR5zunoU52lqpLDua/qIM8idk86xGW
    #    xx2ml43DO/Ya/tVZVok0mO0TUjzJIfPqyvr455IsIut4RlCR9Iq0EDTve2/ZwCuG
    #    hSjpTUFGSiQrR2JK2Evp+o6AETUkBCO1aw0PpQBPDQ==
    #    -----END CERTIFICATE-----

pas-api:
  replicas: 1
  # SDE URL
  #sdeAPIServiceName: mock-sde-service
  #sdeAPIServicePort: 5000
  # Python console logging level. One of DEBUG, INFO, WARNING, ERROR, CRITICAL
  #logLevel: INFO
  # The number of gunicorn workers to spin up
  #workerCount: 4
  # Gunicorn log level
  #gunicornLogLevel: info
  # Name of queue to enqueue SDE jobs
  #sdeQueueName: sde-medium
  # Enable service subcharts and claims for standalone deployment
  useBrokerSubchart: false
  useDatabaseSubchart: false
  useDatastoreSubchart: false
  minio:
    enabled: false
  includeSDESecret: false
  sde:
    # SDE JWT Secret for standalone deployments
    jwtSecret: s3cr3tk3y
    # Secret name for SDE secrets
    #secretName:
    # SDE broker secret config
    broker: {}
      #secretName:
      #passwordSecretKey:
  # PAS Init container config
  admin:
    database: {}
      # Default database name
      #defaultDatabase: postgres
      # The username for a DB admin account
      #user: postgres
      # The secret name where the DB admin account password is stored
      #secretName:
      # The secret key for the DB admin account password
      #passwordSecretKey:
    broker: {}
      # The username for a broker admin account
      #user: rabbit
      # The secret name where the broker admin account password is stored
      #secretName:
      # The secret key for the broker admin account password
      #passwordSecretKey:
  sharedStorage: {}
    # secretName: pas-secrets

  ## Configuration for Sentry
  # sentry:
  #   enabled: false
  #   dsn: https://xxxxxx.ingest.sentry.io/000000
  #   environment: develop
  #   sampleRate: 0.1
  #   traceSampleRate: 0.1


pas-plugin-worker:
  replicas: 1
  # Celery log level. One of DEBUG, INFO, WARNING, ERROR, CRITICAL
  #celeryLogLevel: INFO
  # Number of celery worker processes to launch
  #celeryWorkerCount: 4
  # Max number of celery tasks before recreating the worker.
  #celeryMaxTasksPerChild: 10
  # Disable service subcharts
  useBrokerSubchart: false
  minio:
    enabled: false
  # Broker config
  broker:
    secretName: pas-secrets
    #passwordSecretKey:
  sharedStorage: {}
    # secretName: pas-secrets
  ## Number of seconds for a sync task to perform
  #syncTaskTimeoutSeconds: "1800"


  ## Configuration for Sentry
  # sentry:
  #   enabled: false
  #   dsn: https://xxxxxx.ingest.sentry.io/000000
  #   environment: develop
  #   sampleRate: 0.1
  #   traceSampleRate: 0.1

pas-async-worker:
  replicas: 1
  # Python console logging level. One of DEBUG, INFO, WARNING, ERROR, CRITICAL
  #logLevel: INFO
  # Celery log level. One of DEBUG, INFO, WARNING, ERROR, CRITICAL
  #celeryLogLevel: INFO
  # Number of celery worker processes to launch
  #celeryWorkerCount: 4
  # Max number of celery tasks before recreating the worker.
  #celeryMaxTasksPerChild: 10
  # Disable service subcharts
  useBrokerSubchart: false
  useDatabaseSubchart: false
  minio:
    enabled: false
  # Broker config
  broker:
    secretName: pas-secrets
  # Database config
  database:
    secretName: pas-secrets
  sharedStorage: {}
  # secretName: pas-secrets
  resultBackend: rpc://

  ## Configuration for Sentry
  # sentry:
  #   enabled: false
  #   dsn: https://xxxxxx.ingest.sentry.io/000000
  #   environment: develop
  #   sampleRate: 0.1
  #   traceSampleRate: 0.1

pas-frontend:
  replicas: 1
  # Service name of the PAS API service
  #backendServiceName: pas-api-service
  # Port that the frontend service listens on
  #port: 80
  # Full URL to PAS API service
  #pasBackendUrl: http://pas-api-service:8000
  # TTL for DNS resolutions
  #resolverTTL: 10

  ## Configuration for Sentry
  # sentry:
  #   enabled: false
  #   dsn: https://xxxxxx.ingest.sentry.io/000000
  #   environment: develop
  #   sampleRate: 0.1
  #   traceSampleRate: 0.1

mock-sde:
  secretKey: s3cr3tk3y

# Use mock SDE chart
useMockSDE: false
# Include ingress for standalone deployments
includeIngress: false
