apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: sc-library
  repository: https://sdelements.jfrog.io/artifactory/sde-helm-dev
  version: 0.1.1
description: SD Elements Mock SDE Service
home: https://docker.sdelements.com
icon: https://avatars0.githubusercontent.com/u/739346
keywords:
- sde
- sdelements
- pas
- backend
- python
- wsgi
maintainers:
- email: devops-support@securitycompass.com
  name: Security Compass Technologies Ltd.
  url: https://www.securitycompass.com/
name: mock-sde
sources:
- https://agra.sdelements.com/sd-elements/management_command_system
type: application
version: 0.0.1
