{{- $storageClassName:= default .Values.global.storageClass .Values.brokerStorageClass -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "library.trimmedName" . }}-broker-volume-claim
  labels:
    {{- include "library.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "4Gi" .Values.brokerVolumeSize }}
  {{ if $storageClassName -}}
  storageClassName: {{ $storageClassName }}
  {{- end }}
status: {}
