{{- if .Values.pdb.create }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "library.trimmedName" . }}-sc-datastore
  labels:
    {{- include "library.labels" . | nindent 4 }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "library.trimmedName" . }}
      name: {{ include "datastore.deploymentName" . }}
{{- end }}