{{- $storageClassName := default .Values.global.storageClass .Values.global.backupStorageClass -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "library.trimmedName" . }}-backup-volume-claim
  labels:
    {{- include "library.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ default "30Gi" .Values.global.backupVolumeSize }}
  {{ if $storageClassName -}}
  storageClassName: {{ $storageClassName | quote }}
  {{- end }}
status: {}
