{{- $storageClassName:= default .Values.global.storageClass .Values.dataStorageClass -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "library.trimmedName" . }}-db-volume-claim
  labels:
    {{- include "library.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "30Gi" .Values.dataVolumeSize }}
  {{ if $storageClassName -}}
  storageClassName: {{ $storageClassName | quote }}
  {{- end }}
status: {}
