{{- $deploymentName := include "database.deploymentName" . -}}
{{- $serviceName := include "database.serviceName" . -}}
{{- $port := include "database.port" . -}}
{{- $ipFamilies := default (list "IPv4") .Values.global.ipFamilies -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName | quote }}
  labels:
    service: {{ $serviceName | quote }}
    {{- include "library.labels" . | nindent 4 }}
spec:
  ipFamilies:
  {{- $ipFamilies | toYaml | trim | nindent 2 }}
  ipFamilyPolicy: {{ ternary "PreferDualStack" "SingleStack" (gt (len $ipFamilies) 1) }}
  ports:
  - name: {{ printf "%v" $port | quote }}
    port: {{ int $port }}
    targetPort: {{ int $port }}
  selector:
    name: {{ $deploymentName | quote }}
status:
  loadBalancer: {}

