{{- $mapName := printf "%v-%v" ( include "library.trimmedName" . ) "jitt-resources" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ quote $mapName }}
  labels:
    {{- include "library.labels" . | nindent 4 }}
data:
  {{- range $path, $bytes := .Files.Glob "files-jitt/**.conf" -}}
    {{ printf "conf/%s: |" ( toString $path | trimPrefix "files-jitt/"  ) |  replace "/" "_" | nindent 2 }}
    {{ $.Files.Get $path | nindent 4 }}
  {{- end -}}
