
{{- if and ( not .Values.global.registrySecretName ) ( not .Values.registrySecretName ) }}
{{ include "library.registrySecret" (merge . ( dict "registrySecretPath" "conf/registry-secrets.json")) }}
{{- end }}