{{- $serviceName := printf "%v-%v-%v" ( include "library.trimmedName" . ) "jitt" "service" -}}
{{- $deploymentName := printf "%v-%v" ( include "library.trimmedName" . ) "jitt" -}}
{{- $httpsPort := default 7443 .Values.httpsPort -}}
{{- $ipFamilies := default (list "IPv4") .Values.global.ipFamilies -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName | quote }}
  labels:
    service: {{ $serviceName | quote }}
    {{- include "library.labels" . | nindent 4 }}
spec:
  ipFamilies:
  {{- $ipFamilies | toYaml | trim | nindent 2 }}
  ipFamilyPolicy: {{ ternary "PreferDualStack" "SingleStack" (gt (len $ipFamilies) 1) }}
  ports:
  - name: "https"
    port: {{ int $httpsPort }}
    targetPort: {{ int $httpsPort }}
  selector:
    name: {{ $deploymentName | quote }}
status:
  loadBalancer: {}
