{{- $imagePullPolicy := default .Values.global.imagePullPolicy .Values.imagePullPolicy -}}
{{- $imageRegistryFormat := default "%s/%s-%s-%s:%s" .Values.global.imageRegistryFormat -}}
{{- $imageRegistry := required "An image registry needs to be specified in your configuration values!" ( default .Values.global.imageRegistry .Values.imageRegistry ) -}}
{{- $imageOrganization := required "An image organization needs to be specified in your configuration values!" ( default .Values.global.imageOrganization .Values.imageOrganization ) -}}
{{- $imageSource := default ( default "3rd" .Values.global.imageSource ) .Values.imageSource -}}
{{- $imageName := default "redis" .Values.imageName -}}
{{- $imageTag := default ( default .Chart.AppVersion .Values.global.imageTag ) .Values.imageTag | toString -}}
{{- $uid := default 999 .Values.uid -}}
{{- $gid := default 1000 .Values.gid -}}
{{- $fsgid := default 1000 .Values.fsgid -}}
{{- $deploymentName := printf "%v-%v" ( include "library.trimmedName" . ) "datastore" -}}
{{- $serviceName := printf "%v-%v-%v" ( include "library.trimmedName" . ) "datastore" "service" -}}
{{- $port := default 6379 .Values.port -}}
{{- $dataMountPoint := default "/data" .Values.dataMountPoint -}}
{{- $dataClaimName := printf "%v-%v" ( include "library.trimmedName" . ) "datastore-volume-claim" -}}
{{- $secretName := printf "%v-%v" .Release.Name "redis-secrets" -}}
{{- $mapName := printf "%v-%v" .Release.Name "redis-resources" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName | quote }}
  labels:
    name: {{ $deploymentName | quote }}
    {{- include "library.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.replicas }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      name: {{ $deploymentName | quote }}
      {{- include "library.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ $deploymentName | quote }}
        {{- include "library.selectorLabels" . | nindent 8 }}
    spec:
      {{- if not ((.Values.global.openshift).enabled) }}
      securityContext:
        {{- if not .Values.global.runAsRoot }}
        runAsUser: {{ $uid }}
        runAsGroup: {{ $gid }}
        fsGroup: {{ $fsgid }}
        {{- if semverCompare ">=1.23.0-0" .Capabilities.KubeVersion.GitVersion }}
        fsGroupChangePolicy: "OnRootMismatch"
        {{- end }}
        {{- else }}
        runAsUser: 0
        runAsGroup: 0
        {{- end }}
      {{- end }}
      {{- if .Values.global.enableNodeSelector }}
      nodeSelector:
        customer_name: {{ printf "%v" .Release.Name | quote }}
      {{- end }}
      containers:
      - name: {{ $deploymentName | quote }}
        image: {{ printf $imageRegistryFormat $imageRegistry $imageOrganization $imageSource $imageName $imageTag | quote }}
        imagePullPolicy: {{ $imagePullPolicy }}
        args:  # Override in command line
        - "/usr/local/etc/redis/redis.conf"
        - "--requirepass"
        - "$(REDIS_PASSWORD)"
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: REDIS_DB
          value: {{ default "redis_db" .Values.databaseName }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ $secretName | quote }}
              key: DATASTORE_PASSWORD
        ports:
        - containerPort: {{ int $port }}
        {{- if .Values.resources }}
        resources:
        {{- range $limitType, $resources := $.Values.resources }}
            {{ $limitType }}:
            {{- range $resourceKey, $resourceValue := $resources }}
                {{ $resourceKey }}: {{ $resourceValue }}
            {{- end }}
        {{- end }}
        {{- else }}
        resources: {}
        {{- end }}
        volumeMounts:
        - mountPath: {{ $dataMountPoint | quote }}
          name: datastore
        - mountPath: /usr/local/etc/redis/  # redis.conf
          name: redis-config
          readOnly: true
      imagePullSecrets:
        - name: {{ include "library.registrySecretName" . }}
      restartPolicy: Always
      volumes:
      - name: datastore
        persistentVolumeClaim:
          claimName: {{ $dataClaimName | quote }}
      - name: redis-config
        configMap:
          name: {{ $mapName | quote }}
          items:
          {{- range $path, $bytes := .Files.Glob "files-datastore/*.conf" }}
          - key: {{ printf "conf/%s" ( toString $path | trimPrefix "files-datastore/"  ) | replace "/" "_" }}
            path: {{ toString $path | trimPrefix "files-datastore/" | quote }}
          {{- end }}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName | quote }}
  labels:
    service: {{ $serviceName | quote }}
    {{- include "library.labels" . | nindent 4 }}
spec:
  ports:
  - name: {{ $port | quote }}
    port: {{ int $port }}
    targetPort: {{ int $port }}
  selector:
    name: {{ $deploymentName | quote }}
status:
  loadBalancer: {}
{{ $ca := genCA "datastore-ca" 3650 }}
