{{- if and ( not .Values.global.secretName ) ( not .Values.secretName ) }}
{{- $disableHelmHooks := default false .Values.global.disableHelmHooks -}}
{{- $missingSecretMessage := printf "Database administrator password is required, '--set %v.clientPassword=...'" .Chart.Name -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database.secretName" . }}
  labels:
    {{- include "library.labels" . | nindent 4 }}
  {{- if eq $disableHelmHooks false }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  {{- end }}
data:
  ADMIN_DATABASE_PASSWORD: {{ required $missingSecretMessage .Values.clientPassword | b64enc | quote }}
{{- end }}

{{- if and ( not .Values.global.registrySecretName ) ( not .Values.registrySecretName ) }}
{{ include "library.registrySecret" (merge . ( dict "registrySecretPath" "conf/registry-secrets.json")) }}
{{- end }}
