{{- $dataClaimName := printf "%v-%v" ( include "library.trimmedName" . ) "datastore-volume-claim" -}}
{{- $dataStorageClass := default .Values.global.storageClass .Values.dataStorageClass -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $dataClaimName | quote }}
  labels:
    {{- include "library.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "10Gi" .Values.dataVolumeSize }}
  {{ if $dataStorageClass -}}
  storageClassName: {{ $dataStorageClass | quote }}
  {{- end }}
status: {}
