{{ include "library.registrySecret" (merge . ( dict "registrySecretName" "security-compass-secret" "registrySecretPath" "conf/registry-secrets.json")) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-secrets
  labels:
    {{- include "library.labels" . | nindent 4 }}
  {{- if not .Values.global.disableHelmHooks }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  {{- end }}
data:
  DATASTORE_PASSWORD: {{ required "Datastore password is required, '--set clientPassword'" .Values.clientPassword  | b64enc}}
