{{- $tlsEnabled := default "false" .Values.tlsEnabled -}}
{{- $brokerHost := default ( printf "%v-%v" ( include "library.trimmedName" . ) "broker-service" ) .Values.global.broker.host -}}
{{- $brokerPort := default (ternary 5671 5672 ( eq $tlsEnabled "true" )) .Values.global.broker.port -}}
{{- $brokerServer := printf "%v:%v" $brokerHost $brokerPort -}}
{{- $brokerVhost := default (default "rabbit" .Values.global.broker.adminVhost) .Values.global.pas.broker.vhost -}}
{{- $brokerUser := default ( default ( default "rabbit" .Values.global.broker.adminClientUser ) .Values.global.pas.broker.user ) .Values.broker.user -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-broker-env-configmap
  labels:
    {{ include "library.labels" . | nindent 4 }}
data:
  PLUGIN_SERVICE_BROKER_SERVER: {{ $brokerServer }}
  PLUGIN_SERVICE_BROKER_VHOST: {{ $brokerVhost }}
  PLUGIN_SERVICE_BROKER_USER: {{ $brokerUser }}
  {{ if .Values.resultBackend}}
  PLUGIN_SERVICE_RESULT_BACKEND: {{ .Values.resultBackend }}
  {{ end }}
  {{ if .Values.pluginServiceQueueName}}
  PLUGIN_SERVICE_QUEUE_NAME: {{ .Values.pluginServiceQueueName }}
  {{ end }}

  PAS_ASYNC_WORKER_BROKER_SERVER: {{ $brokerServer }}
  PAS_ASYNC_WORKER_BROKER_VHOST: {{ $brokerVhost }}
  PAS_ASYNC_WORKER_BROKER_USER: {{ $brokerUser }}
  {{ if .Values.asyncWorkerQueueName}}
  PAS_ASYNC_WORKER_QUEUE_NAME: {{ .Values.asyncWorkerQueueName }}
  {{ end }}
