{{- $claimName := printf "%v-%v" ( include "library.trimmedName" . ) "pas-custom-plugin-volume-claim" -}}
{{- $storageClass := default .Values.global.storageClass .Values.storageClass -}}
{{- if and (not (or .Values.global.pas.pluginVolumeClaimName .pluginVolumeClaimName)) .Values.includePluginVolumeClaim -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $claimName | quote }}
  labels:
    {{- include "library.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ default "2Gi" .Values.global.pas.customPluginVolumeSize }}
  {{ if $storageClass -}}
  storageClassName: {{ $storageClass | quote }}
  {{- end }}
status: {}
{{- end -}}
