{{- $configMapName := include "cam.configMapName" . -}}
{{- $initConfigMapName := include "cam.initConfigMapName" . -}}
{{- $enableSdeTls := eq ( include "enableSdeTls" . ) "true" -}}
{{- $sdeWorkerScheme := ternary "https" "http" $enableSdeTls -}}
{{- $sdeWorkerPort := default 8080 .Values.sde.port -}}
{{- $sdeWorker := default "worker-10" .Values.sde.worker }}
{{- $sdeApiPath := default "/api/v2" .Values.sde.apiPath }}
{{- $sdeUrl := printf "%v://%v-%v-%v:%v%v" $sdeWorkerScheme ( include "library.trimmedName" . ) $sdeWorker "service" $sdeWorkerPort $sdeApiPath -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ quote $initConfigMapName }}
  labels:
    {{- include "library.labels" . | nindent 4 }}
data:
  DATABASE_REQUIRE_SSL: {{ default "false" .Values.databaseUseSsl | quote }}
  BROKER_REQUIRE_SSL: {{ default "false" .Values.brokerUseSsl | quote }}
  SDE_OPENSHIFT_ENABLED: {{ ternary "false" "true"  (not (.Values.global.openshift).enabled) | quote }}
  ADMIN_BROKER_USER: {{ default (default "rabbit" (.Values.global.broker).adminClientUser) .Values.brokerAdminUser | quote }}
  BROKER_HOST: {{ default ( printf "%v-%v" ( include "library.trimmedName" . ) "broker-headless") .Values.brokerHost | quote }}
  SERVICE_DATABASE_USER: {{ default "cam" .Values.databaseUser | quote }}
  SERVICE_DATABASE_NAME: {{ printf "%v" ( include "cam.sde.dbName" . ) }}
  SERVICE_SCHEMA_NAME: {{ default "cam" .Values.databaseSchemaName | quote }}
  SERVICE_BROKER_USER: {{ default "cam" .Values.brokerUser | quote }}
  SERVICE_CREATE_POSTGRES_SCHEMA: "true"
  SERVICE_CREATE_POSTGRES_USER: "true"
  SERVICE_CREATE_BROKER_USER: "true"
  SDE_DATABASE_NAME: {{ printf "%v" ( include "cam.sde.dbName" . ) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ quote $configMapName }}
  labels:
    {{- include "library.labels" . | nindent 4 }}
data:
  CAM_PORT: {{ default "3000" .Values.port | quote }}
  CAM_DATABASE_HOST: {{ default ( printf "%v-%v" ( include "library.trimmedName" . ) "database-service") .Values.databaseHost | quote }}
  CAM_DATABASE_PORT: {{ default "5432" .Values.databasePort | quote }}
  CAM_DATABASE_USER: {{ default "cam" .Values.databaseUser | quote }}
  CAM_SCHEMA_NAME: {{ default "cam" .Values.databaseSchemaName | quote }}
  CAM_BROKER_USER: {{ default "cam" .Values.brokerUser | quote }}
  CAM_BROKER_VHOSTS: {{ default "cam" .Values.brokerVhost | quote }}
  SDE_DATABASE_NAME: {{ printf "%v" ( include "cam.sde.dbName" . ) }}
  API_PREFIX: {{ default "api/asset" .Values.apiPrefix | quote }}
  DATABASE_REQUIRE_SSL: {{ default "false" .Values.databaseUseSsl | quote }}
  BROKER_REQUIRE_SSL: {{ default "false" .Values.brokerUseSsl | quote }}
  SDE_OPENSHIFT_ENABLED: {{ ternary "false" "true"  (not (.Values.global.openshift).enabled) | quote }}
  ADMIN_BROKER_USER: {{ default (default "rabbit" (.Values.global.broker).adminClientUser) .Values.brokerAdminUser | quote }}
  BROKER_HOST: {{ default ( printf "%v-%v" ( include "library.trimmedName" . ) "broker-headless") .Values.brokerHost | quote }}
  SDE_CORE_API_URL: {{ $sdeUrl | quote }}
