### Default values for the Example (example) Helm Chart.
### This is a YAML-formatted file.
### Declare variables to be passed into your templates.

global:
  enabled: true
  enableNestedDependencies: false

  ## Default image tag.
  ## The version of container images for SDE to run
  ## Ref: https://docs.sdelements.com
  ##
  # imageTag: latest

  ## Provide a name in place of `sde` for `app:` labels
  ##
  #nameOverride: ""

  ## Provide a name to substitute for the full names of resources
  ##
  #fullnameOverride: ""

  ## Configuration options and crentials to fetch images from private
  ## registries/repositories. These are provided by SDElements support staff on
  ## request upon purchase of the SDElements product.
  ##
  imageRegistry: sdelements.jfrog.io

  # Format: $imageRegistry $imageOrganization $imageSource $imageName $imageTag
  # sdelements.jfrog.io/sde-docker-prod/sde/postgres-bespoke:latest
  imageRegistryFormat: "%s/sde-docker-%s/%s/%s:%s"
  #imageRegistryUsername: acmecorp
  #imageRegistryPassword: myPassword
  imageOrganization: prod  # dev/staging/prod
  imageSource: sde
  imagePullPolicy: Always
  #storageClass: aws-ebs

  ## Configuration for running on Openshift
  # openshift:
  #   enabled: false

commands: {}
# jit: "off"

replicas: 1
#databaseName: myDbName
#port: 5432
#dataStorageClass: aws-ebs
#dataMountPoint: /var/lib/postgresql/data
#dataDir: pgdata
#dataVolumeSize: 30Gi
#imageTag: latest
#imagePullPolicy: Always
#imageSource: dccsr
#imageName: postgres-bespoke
#clientCertificatePath: certs/myDBClientCert.pem
#clientKeyPath: certs/myDBClientKey.pem
#caCertificatePath: certs/myCACert.pem
#caKeyPath: certs/myCAKey.pem
#serverCertificatePath: myDBServerCert.pem
#serverKeyPath: myDBServerKey.pem
#clientPassword: myPassword
#clientUser: sde
#shm_size: 256Mi
#databaseTopologySpread:
#  enabled: false
#  maxSkew: 1
#  topologyKey: topology.kubernetes.io/zone
#  whenUnsatisfiable: ScheduleAnyway

## User/Group options
# uid: 33
# gid: 33
# fsgid: 33

## Container options
resources:
  requests:
    memory: 512Mi

networkPolicies:
  database:
    podSelector:
      matchLabels:
        name: "{{ include \"library.trimmedName\" . }}-database"
    ingress:
      - selectors:
          - podSelector:
              matchLabels:
                name: "{{ include \"library.trimmedName\" . }}-worker-10"
          - podSelector:
              matchLabels:
                name: "{{ include \"library.trimmedName\" . }}-worker-17"
          - podSelector:
              matchLabels:
                name: "{{ include \"library.trimmedName\" . }}-worker-15-sde-medium"
          - podSelector:
              matchLabels:
                name: "{{ include \"library.trimmedName\" . }}-worker-18-sde-low"
          - podSelector:
              matchLabels:
                name: "{{ include \"library.trimmedName\" . }}-reporting"
          - podSelector:
              matchLabels:
                name: "{{ include \"library.trimmedName\" . }}-pas-async-worker"
          - podSelector:
              matchLabels:
                name: "{{ include \"library.trimmedName\" . }}-pas-api"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-alm-hourly"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-alm-daily"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-alm-weekly"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-alm-monthly"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-cancel-external-sync-jobs"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-database-backup"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-clear-expired-sessions"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-refresh-task-relevance"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-metrics"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-send-new-relevant-task-notifications"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-time-since"

        ports:
          - port: '{{ include "database.port" . }}'
