{{- $sdeAPIServiceMethod := default "http" .Values.sdeAPIServiceMethod -}}
{{- $sdeAPIServiceName := required "SDE API service name is required" .Values.sdeAPIServiceName -}}
{{- $sdeAPIServicePort := required "SDE API service port is required" .Values.sdeAPIServicePort -}}

# Sentry variables
{{- $sentryEnabled := default false (eq ((.Values.sentry).enabled | toString) "<nil>" | ternary (.Values.global.sentry).enabled (.Values.sentry).enabled) -}}
{{- $sentryDSN := (.Values.sentry).dsn }}
{{- $sentryEnvironment := default .Release.Namespace (default (.Values.global.sentry).environment (.Values.sentry).environment) }}
{{- $sentrySampleRate := default 0.1 (default (.Values.global.sentry).sampleRate (.Values.sentry).sampleRate) }}
{{- $sentryTraceSampleRate := default 0.1 (default (.Values.global.sentry).traceSampleRate (.Values.sentry).traceSampleRate) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-env-configmap
  labels:
    {{ include "library.labels" . | nindent 4 }}
data:
  BASE_URL: {{ default (default "/pas" .Values.global.pas.baseUrl) .Values.pasBaseUrl | quote }}
  SDE_URL: {{ printf "%v://%v-%v:%v" $sdeAPIServiceMethod ( include "library.trimmedName" . ) $sdeAPIServiceName $sdeAPIServicePort | quote }}
  CUSTOM_PLUGINS_API_TOGGLE: {{ default (default "true" .Values.global.pas.enableCustomPlugins) .Values.enableCustomPlugins | quote }}
  PLUGIN_MAX_SIZE_BYTES: {{ default (default "10000000"  .Values.global.pas.maxPluginFileSize) .Values.maxPluginFileSize | quote }}
  PAS_CONSOLE_LOG_LEVEL: {{ default "INFO" .Values.logLevel | quote }}
  WEB_CONCURRENCY: {{ default 4 .Values.workerCount | quote }}
  LOG_LEVEL: {{ default "info" .Values.gunicornLogLevel | quote }}
  SDE_OPENSHIFT_ENABLED: {{ ternary "false" "true"  (not (.Values.global.openshift).enabled) | quote }}
  {{ if $sentryEnabled }}
  SDE_PAS_API_SENTRY_DSN: {{ required "SDE_PAS_API_SENTRY_DSN must be specified if Sentry configuration is enabled." $sentryDSN | quote }}
  SDE_SENTRY_ENVIRONMENT: {{ $sentryEnvironment | quote }}
  SDE_SENTRY_SAMPLE_RATE: {{ $sentrySampleRate | quote }}
  SDE_SENTRY_TRACE_SAMPLE_RATE: {{ $sentryTraceSampleRate | quote }}
  {{ end }}
  {{- if .Values.global.thirdPartyCACertificates.enabled }}
  TRUST_THIRDPARTY_CA_CERTS: "true"
  {{- end }}
