apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-init-env-configmap
  labels:
    {{- include "library.labels" . | nindent 4 }}
data:
  # Broker Variables
  BROKER_HOST: {{ default ( printf "%v-%v" ( include "library.trimmedName" . ) "broker-service" ) .Values.global.broker.host | quote }}
  BROKER_USER: {{ include "pas.brokerUser" (dict "root" . "dot" .Values) | trim | quote }}
  ADMIN_BROKER_USER: {{ default (default "rabbit" .Values.global.broker.adminClientUser) .Values.admin.broker.user | quote }}
  PROVISIONING_BROKER_VHOSTS: {{ include "pas.brokerVhost" (dict "root" . "dot" .Values) | trim | quote }}
  BROKER_REQUIRE_SSL: {{ default "false" .Values.global.broker.requireSSL | quote }}
