{{- if .Values.includeSDESecret -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sde-secrets
  labels:
    {{- include "library.labels" . | nindent 4 }}
  {{- if not .Values.global.disableHelmHooks }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  {{- end }}
data:
  SDE_JWT_SECRET: {{ required "SDE JWT secret is required, '--set sde.jwtSecret'" .Values.sde.jwtSecret | b64enc}}
{{- end -}}
