{{- if and ( not .Values.global.secretName ) ( not .Values.secretName ) }}
{{- $disableHelmHooks := default false .Values.global.disableHelmHooks -}}
{{- $secretName := printf "%v-%v" .Release.Name "pas-secrets" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName | quote }}
  labels:
    {{- include "library.labels" . | nindent 4 }}
  {{- if eq $disableHelmHooks false }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  {{- end }}
data:
  PAS_BROKER_PASSWORD: {{ required "PAS broker password is required, '--set global.pas.broker.password'" .Values.global.pas.broker.password | b64enc }}
  PAS_DATABASE_PASSWORD: {{ required "PAS database password is required, '--set global.pas.database.password'" .Values.global.pas.database.password | b64enc }}
  {{- if not (or .Values.global.sharedStorage.secretName .Values.global.pas.sharedStorage.secretName .Values.sharedStorage.secretName) }}
  PAS_S3_ACCESS_KEY: {{ required "PAS S3 Access key is required, '--set global.pas.sharedStorage.s3AccessKey'" .Values.global.pas.sharedStorage.s3AccessKey | b64enc }}
  PAS_S3_SECRET_ACCESS_KEY: {{ required "PAS S3 Secret key is required, '--set global.pas.sharedStorage.s3SecretKey'" .Values.global.pas.sharedStorage.s3SecretKey | b64enc }}
  {{- end }}
{{ end }}

{{- if and ( not .Values.global.registrySecretName ) ( not .Values.registrySecretName ) }}
{{ include "library.registrySecret" (merge . ( dict "registrySecretPath" "conf/registry-secrets.json")) }}
{{- end }}
