{{- $serviceName := printf "%v-%v-%v" ( include "library.trimmedName" . ) "mailer" "service" -}}
{{- $deploymentName := (include "mail.deploymentName" .) -}}
{{- $ipFamilies := default (list "IPv4") .Values.global.ipFamilies -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName | quote }}
  labels:
    service: {{ $serviceName | quote }}
    {{- include "library.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ipFamilies:
  {{- $ipFamilies | toYaml | trim | nindent 2 }}
  ipFamilyPolicy: {{ ternary "PreferDualStack" "SingleStack" (gt (len $ipFamilies) 1) }}
  ports:
  - name: smtp
    port: {{ default "25" .Values.port }}
    targetPort: {{ default 8025 ((.Values.config).localPort) }}
    protocol: TCP
  selector:
    name: {{ $deploymentName | quote }}
status:
  loadBalancer: {}
