{{- $serviceAccountName := (include "mail.serviceAccountName" .) -}}
{{- if .Values.createServiceAccount -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName | quote }}
  labels:
{{ include "library.labels" . | nindent 4 }}
{{- end -}}
