{{- $values := index .Values "config.tls" -}}
{{- $useCertValues := and ( hasKey $values "tlsCertificate" ) ( hasKey $values "tlsKey" ) -}}
{{- $useCertPaths := and ( hasKey $values "tlsCertificatePath" ) ( hasKey $values "tlsKeyPath" ) -}}
{{- $tlsSecretName := printf "%v-%v" .Chart.Name "tls-secrets" -}}
{{- if and $useCertPaths $useCertValues }}
{{- fail "SDE's Web TLS resources can be specified either by file paths or values, not both." }}
{{- else if and ( hasKey $values "tlsCertificatePath") ( not ( hasKey $values "tlsKeyPath") )  }}
{{- fail "Can't use web.tlsCertificatPath without specifying web.tlsKeyPath." }}
{{- else if and ( hasKey $values "tlsKeyPath") ( not ( hasKey $values "tlsCertificatePath") )  }}
{{- fail "Can't use web.tlsKeyPath without specifying web.tlsCertificatePath." }}
{{- else if and ( hasKey $values "tlsCertificate") ( not ( hasKey $values "tlsKey") ) }}
{{- fail "Can't use web.tlsCertificate without specifying web.tlsKey." }}
{{- else if and ( hasKey $values "tlsKey") ( not ( hasKey $values "tlsCertificate") ) }}
{{- fail "Can't use web.tlsKey without specifying web.tlsCertificate." }}
{{- end }}
{{- if or $useCertValues $useCertPaths }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $tlsSecretName | quote }}
  labels:
    {{- include "library.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: |-
    {{- if $useCertValues }}
    {{ $values.tlsCertificate | b64enc -}}
    {{ else }}
      {{- if not (.Files.Glob $values.tlsCertificate) }}
        {{ fail (printf "File with path %s does not exist." $values.tlsCertificate) }}
      {{- end }}
    {{- range $path, $_ :=  .Files.Glob  $values.tlsCertificate }}
    {{ ( $.Files.Get $path ) | b64enc }}
    {{- end }}
    {{- end }}
  tls.key: |-
    {{- if $useCertValues }}
    {{ $values.tlsKey | b64enc }}
    {{ else }}
      {{- if not (.Files.Glob $values.tlsKey) }}
        {{ fail (printf "File with path %s does not exist." $values.tlsKey) }}
      {{- end }}
    {{- range $path, $_ :=  .Files.Glob  $values.tlsKey }}
    {{ ( $.Files.Get $path ) | b64enc }}
    {{- end }}
    {{- end }}
{{- end }}
