### Default values for the Example (example) Helm Chart.
### This is a YAML-formatted file.
### Declare variables to be passed into your templates.

## Example specific options
global:
  enableNestedDependencies: false
  ## SDElements image tag.
  ## The version of SDE to run, Ref: https://docs.sdelements.com
  # imageTag: latest

  ## Provide a name in place of `sde` for `app:` labels
  ##
  #nameOverride: ""

  ## Provide a name to substitute for the full names of resources
  ##
  #fullnameOverride: ""

  ## Configuration options and crentials to fetch images from private
  ## registries/repositories. These are provided by SDElements support staff on
  ## request upon purchase of the SDElements product.
  ##
  imageRegistry: sdelements.jfrog.io

  # Format: $imageRegistry $imageOrganization $imageSource $imageName $imageTag
  # sdelements.jfrog.io/sde-docker-prod/sde/postgres-bespoke:latest
  imageRegistryFormat: "%s/sde-docker-%s/%s/%s:%s"
  #imageRegistryUsername: acmecorp
  #imageRegistryPassword: myPassword
  imageOrganization: prod  # dev/staging/prod
  imageSource: sde
  imagePullPolicy: IfNotPresent
  broker:
    enabled: true
    #adminClientUser: admin
    #adminClientPassword: myRabbitMQUserPassword
    #adminVhost: admin
  useStandalone: true

  ## Configuration for running on Openshift
  # openshift:
  #   enabled: false

## Message broker (rabbitmq)
#imageName: rabbitmq
#imageTag: 3-alpine
#imagePullPolicy: Always
#imageSource: dccsr
replicas: 1
#caCertificatePath: certs/myCACert.pem
#caKeyPath: certs/myCAKey.pem
#serverCertificatePath: myDBServerCert.pem
#serverKeyPath: myDBServerKey.pem
## Connection parameters
#host: mq

#brokerStorageClass: aws-ebs
#brokerVolumeSize: 4G

## User/Group options
# uid: 100
# gid: 101
# fsgid: 101

## Container options
resources:
  requests:
    memory: 128Mi

networkPolicies:
  broker:
    podSelector:
      matchLabels:
        name: "{{ include \"library.trimmedName\" . }}-broker"
    ingress:
      - selectors:
          - podSelector:
              matchLabels:
                name: "{{ include \"library.trimmedName\" . }}-worker-10"
          - podSelector:
              matchLabels:
                name: "{{ include \"library.trimmedName\" . }}-worker-17"
          - podSelector:
              matchLabels:
                name: "{{ include \"library.trimmedName\" . }}-worker-15-sde-medium"
          - podSelector:
              matchLabels:
                name: "{{ include \"library.trimmedName\" . }}-worker-18-sde-low"
          - podSelector:
              matchLabels:
                name: "{{ include \"library.trimmedName\" . }}-pas-async-worker"
          - podSelector:
              matchLabels:
                name: "{{ include \"library.trimmedName\" . }}-pas-plugin-worker"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-alm-hourly"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-alm-daily"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-alm-weekly"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-alm-monthly"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-cancel-external-sync-jobs"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-database-backup"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-clear-expired-sessions"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-refresh-task-relevance"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-metrics"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-send-new-relevant-task-notifications"
          - podSelector:
              matchLabels:
                app: "{{ include \"library.trimmedName\" . | trunc 10 }}-job-time-since"
        ports:
          - port: '{{ index .Values "port" | int | default 5672 }}'
      - selectors:
          - podSelector:
              matchLabels:
                name: "{{ include \"library.trimmedName\" . }}-pas-api"
        ports:
          - port: '{{ index .Values "port" | int | default 5672 }}'
          - port: '{{ index .Values "managementPort" | int | default 15672 }}'
