{{/*
Template to create the network policy.
Requires root context.
*/}}
{{- define "library.networkPolicy" -}}
{{- $networkPolicies := .Values.networkPolicies  -}}
{{- if (and .Values.global.networkIsolation $networkPolicies) }}

{{- $releaseName := printf "%v" ( include "library.trimmedName" . ) -}}
{{- $releaseNameShort := printf "%v" ( include "library.trimmedName" . | trunc 10 ) -}}

{{- $ingressFiltering := false }}
{{- $egressFiltering := false }}

{{- if eq .Values.global.networkIsolation "ingress" }}
  {{- $ingressFiltering = true }}
{{- else if eq .Values.global.networkIsolation "full" }}
  {{- $ingressFiltering = true }}
  {{- $egressFiltering = true }}
{{- end }}

{{- if (or $ingressFiltering $egressFiltering) }}

{{ range $resourceName, $resourceSpec := $networkPolicies }}
{{ $resourceSpec = fromYaml ( tpl (toYaml $resourceSpec) $ ) }}
---
kind: NetworkPolicy
apiVersion: "networking.k8s.io/v1"
metadata:
  name: "{{ $releaseNameShort }}-np-{{ $resourceName }}"
  {{- if $resourceSpec.annotations }}
  annotations:
    {{ toYaml $resourceSpec.annotations | indent 4 | trim }}
  {{- end }}
  labels:
    name: "{{ $releaseName }}-np-{{ $resourceName }}"
    {{- include "library.labels" $ | nindent 4 }}
    {{- if $resourceSpec.labels }}
    {{ toYaml $resourceSpec.labels | indent 4 | trim }}
    {{- end }}
spec:
  {{- if $resourceSpec.podSelector }}
  podSelector:
    matchLabels:
      {{ toYaml $resourceSpec.podSelector.matchLabels | indent 6 | trim }}
  {{- end }}

  {{- if or $resourceSpec.ingress $resourceSpec.egress }}
  policyTypes:
    {{- if and $resourceSpec.ingress $ingressFiltering }}
    - Ingress
    {{- end }}

    {{- if and $resourceSpec.egress $egressFiltering }}
    - Egress
    {{- end }}
  {{- end }}

  {{- if and $resourceSpec.egress $egressFiltering }}
  egress:
    {{-  range $rule := $resourceSpec.egress }}
    - to:
        {{ toYaml $rule.selectors | indent 8 | trim }}
      {{- if $rule.ports }}
      ports:
        {{ toYaml $rule.ports | indent 8 | replace "\"" "" | trim }}
      {{- end }}
    {{- end }}
  {{- end }}

  {{- if and $resourceSpec.ingress $ingressFiltering }}
  ingress:
    {{-  range $rule := $resourceSpec.ingress }}
    - from:
        {{ toYaml $rule.selectors | indent 8 | trim }}
      {{- if $rule.ports }}
      ports:
        {{ toYaml $rule.ports | indent 8 | replace "\"" "" | trim }}
      {{- end }}
    {{- end }}
  {{- end }}

{{- end }}
{{- end }}
{{- end }}
{{- end }}

