### Default values for the SDE Worker Helm Chart.
### This is a YAML-formatted file.
### Declare variables to be passed into your templates.

## Options & settings accessible by all charts
global:
  ## Default image tag.
  ## The version of container images for SDE to run
  ## Ref: https://docs.sdelements.com
  ##
  # imageTag: latest

  ## Provide a name in place of `sde` for `app:` labels
  ##
  #nameOverride: ""

  ## Provide a name to substitute for the full names of resources
  ##
  #fullnameOverride: ""

  ## Configuration options and crentials to fetch images from private
  ## registries/repositories. These are provided by SDElements support staff on
  ## request upon purchase of the SDElements product.
  ##
  imageRegistry: docker-dev.sdelements.com

  # Format: $imageRegistry $imageOrganization $imageSource $imageName $imageTag
  # docker.sdelements.com / default_organization - (sde/3rd) - cert-creator : latest
  # docker-dev.sdelements.com / dev _ (sde/3rd) / cert-creator : latest
  imageRegistryFormat: "%s/%s_%s/%s:%s"
  imageRegistryUsername: acmecorp
  imageRegistryPassword: SuperSecretPassword
  imageOrganization: dev
  imagePullPolicy: IfNotPresent

# imageTag: latest
# imageSource: dccsr
# imagePullPolicy: Always
# enableTls: true

replicas: 1
# port: 0
# tlsPort: 6379
#clientPassword: mySuperDatastorePass
#dataVolumeSize: 10Gi

## Container options
#resources: {}